[tools]
actionlint = "1.7.12"
"cargo:cargo-deny" = "0.19.9"
"cargo:cargo-deb" = "3.7.0"
zig = "0.16.0"

[tool_alias]
cargo-nextest = "github:nextest-rs/nextest"
cargo-zigbuild = "github:rust-cross/cargo-zigbuild"

[tools.cargo-nextest]
version = "cargo-nextest-0.9.138"
matching = "cargo-nextest"
rename_exe = "cargo-nextest"

[tools.cargo-zigbuild]
version = "0.23.0"
matching = "cargo-zigbuild"
rename_exe = "cargo-zigbuild"

[settings]
idiomatic_version_file_enable_tools = ["rust"]

[tasks.fmt]
run = "cargo fmt --all --check"

[tasks.lint]
run = "cargo clippy --workspace --all-targets --locked -- -D warnings"

[tasks.test]
run = "cargo nextest run --workspace --locked --color=always"

[tasks.actionlint]
run = "actionlint"

[tasks.deny]
run = "cargo deny check advisories"

[tasks.check]
depends = ["fmt", "actionlint", "deny", "lint", "test"]
