#!/usr/bin/env bash
# Generated by github-actions-generator. Regenerate; do not hand-edit.
# Fail closed on unsafe workflow composition. This helper contains only
# workflow-policy checks; it never evaluates project commands.
set -euo pipefail

readonly WORKFLOWS="${WORKFLOW_ROOT:-${GITHUB_WORKSPACE:-$PWD}}/.github/workflows"
readonly PROJECT_CONFIG="${WORKFLOW_ROOT:-${GITHUB_WORKSPACE:-$PWD}}/.github/ci/project.toml"
runner_mode=""
if [[ -f "$PROJECT_CONFIG" ]]; then
  runner_mode="$(awk -F'"' '/^runners = "/ { print $2; exit }' "$PROJECT_CONFIG")"
fi
status=0
current_workflow=""
shopt -s nullglob
verify_action() {
  local action="$1" single_quote="'" double_quote='"'
  action="${action#"${action%%[!$' \t']*}"}"
  action="${action%%[[:space:]]*}"
  if [[ "$action" == "$double_quote"*"$double_quote" ]]; then
    action="${action#"$double_quote"}"
    action="${action%"$double_quote"}"
  elif [[ "$action" == "$single_quote"*"$single_quote" ]]; then
    action="${action#"$single_quote"}"
    action="${action%"$single_quote"}"
  fi
  if [[ "$action" =~ ^\./\.github/workflows/ci-[A-Za-z0-9._-]+\.yml$ ]]; then
    : # Only generator-owned local reusable workflows are allowed.
  elif [[ "$action" == */.github/workflows/* ]]; then
    printf '%s: reusable workflow must be an approved local generated workflow: %s\n' "$current_workflow" "$action" >&2
    status=1
  elif ! [[ "$action" =~ ^[-_./A-Za-z0-9]+@[0-9a-f]{40}$ ]]; then
    printf '%s: action is not a full SHA pin: %s\n' "$current_workflow" "$action" >&2
    status=1
  fi
}

for workflow in "$WORKFLOWS"/*.yml "$WORKFLOWS"/*.yaml; do
  current_workflow="$workflow"
  block_indent=-1
  while IFS= read -r line || [[ -n "$line" ]]; do
    leading="${line%%[!$' \t']*}"
    indent=${#leading}
    if (( block_indent >= 0 )); then
      if [[ -z "${line//[$' \t']/}" || $indent -gt $block_indent ]]; then continue; fi
      block_indent=-1
    fi
    body="${line#"$leading"}"
    if [[ "$body" =~ ^-[[:space:]]+ ]]; then
      body="${body#-}"
      body="${body#"${body%%[!$' \t']*}"}"
    fi
    if [[ "$body" =~ ^[^[:space:]#:]+:[[:space:]]*[\|\>][-+0-9]*([[:space:]]*#.*)?$ ]]; then
      block_indent=$indent
      continue
    fi
    if [[ "$body" =~ ^pull_request_target[[:space:]]*: ]]; then
      printf '%s: pull_request_target is forbidden\n' "$workflow" >&2
      status=1
    fi
    if [[ "$body" =~ ^uses[[:space:]]*:[[:space:]]*(.*)$ ]]; then
      verify_action "${BASH_REMATCH[1]}"
    fi
  done < "$workflow"
  if grep -Eq '^([[:space:]]*)runs-on:[[:space:]]*.*(self-hosted|velnor)' "$workflow"; then
    if [[ "$runner_mode" != velnor && "$runner_mode" != both ]] \
      && { ! grep -Eq "github.ref == 'refs/heads/[A-Za-z0-9._-]+'" "$workflow" \
        || ! grep -Eq "github.event_name == '(push|schedule|workflow_dispatch)'" "$workflow"; }; then
      printf '%s: self-hosted jobs require a default-branch trusted-event gate\n' "$workflow" >&2
      status=1
    fi
  fi
done
exit "$status"
