#!/usr/bin/env bash
# Generated by github-actions-generator. Regenerate; do not hand-edit.
# Execute checked-in TOML CI configuration; do not evaluate project metadata.
set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)" || exit $?
readonly ROOT
readonly CONFIG="$ROOT/.github/ci/project.toml"
die() { printf 'CI runner error: %s\n' "$*" >&2; exit 2; }

all_unit_ids() {
  awk '
    /^\[\[unit\]\]/ { next }
    /^id = / {
      id=$0
      sub(/^id = "/, "", id)
      sub(/"$/, "", id)
      print id
    }
  ' "$CONFIG"
}

depends_on_rows() { toml_array_rows depends_on; }

validate_config() {
  [[ -s "$CONFIG" ]] || die "missing CI configuration: $CONFIG"
  local id dep owner count=0 ids dependencies watch commands
  declare -A known=()
  ids="$(all_unit_ids)" || die 'failed to parse unit ids'
  while IFS= read -r id; do
    [[ -n "$id" ]] || continue
    [[ "$id" =~ ^[a-z0-9][a-z0-9-]*$ ]] || die "invalid unit id: $id"
    [[ -z "${known[$id]:-}" ]] || die "duplicate unit id: $id"
    known["$id"]=1
    count=$((count + 1))
  done <<< "$ids"
  (( count > 0 )) || die 'project.toml declares no units'
  dependencies="$(depends_on_rows)" || die 'failed to parse unit dependencies'
  while IFS=$'\t' read -r owner dep; do
    [[ -n "$owner" || -n "$dep" ]] || continue
    [[ -n "$owner" && -n "$dep" ]] || die 'depends_on contains an empty value'
    [[ -n "${known[$owner]:-}" ]] || die "depends_on owner is unknown: $owner"
    [[ -n "${known[$dep]:-}" ]] || die "$owner depends on unknown unit: $dep"
    [[ "$owner" != "$dep" ]] || die "unit cannot depend on itself: $owner"
  done <<< "$dependencies"
  while IFS= read -r id; do
    [[ -n "$id" ]] || continue
    watch="$(commands_for_unit "$id" watch)" || die "failed to parse watch paths for $id"
    commands="$(commands_for_unit "$id" pr_commands)" || die "failed to parse PR commands for $id"
    [[ -n "$watch" ]] || die "unit has no watch paths: $id"
    [[ -n "$commands" ]] || die "unit has no PR commands: $id"
    commands="$(commands_for_unit "$id" full_commands)" || die "failed to parse full commands for $id"
    [[ -n "$commands" ]] || die "unit has no full commands: $id"
  done <<< "$ids"
}

# The generator emits one-line TOML arrays of basic strings. Parse only that
# narrow, documented format; escaped quotes and commas remain part of values.
toml_array_rows() {
  local field="$1"
  awk -v field="$field" '
    function emit_values(value, position, character, escaped, quoted, item) {
      sub(/^[^=]*= \[/, "", value)
      sub(/\][[:space:]]*$/, "", value)
      escaped=0
      quoted=0
      item=""
      for (position = 1; position <= length(value); position++) {
        character=substr(value, position, 1)
        if (escaped) {
          if (character == "n") item=item "\n"
          else if (character == "r") item=item "\r"
          else if (character == "t") item=item "\t"
          else if (character == "b") item=item sprintf("%c", 8)
          else if (character == "f") item=item sprintf("%c", 12)
          else item=item character
          escaped=0
        } else if (character == "\\") {
          escaped=1
        } else if (character == "\"") {
          if (quoted) print id "\t" item
          quoted=!quoted
          item=""
        } else if (quoted) {
          item=item character
        }
      }
    }
    /^\[\[unit\]\]/ { id=""; next }
    /^id = / {
      id=$0
      sub(/^id = "/, "", id)
      sub(/"$/, "", id)
      next
    }
    id != "" && $0 ~ ("^" field " = \\[") { emit_values($0) }
  ' "$CONFIG"
}

watch_rows() { toml_array_rows watch; }
matches_pattern() {
  local file="$1" pattern="$2"
  # Bash conditional patterns provide the needed *, ?, and [] semantics
  # without eval; * also spans slashes, matching repository-relative paths.
  # shellcheck disable=SC2053
  [[ "$file" == $pattern ]]
}

selected_units() {
  local scope="$1" all_ids dependencies watch selected_rows
  all_ids="$(all_unit_ids)" || die 'failed to parse unit ids'
  dependencies="$(depends_on_rows)" || die 'failed to parse unit dependencies'
  if [[ "$scope" == full ]]; then ordered_units "$all_ids" "$dependencies"; return; fi
  local base="${BASE_SHA:-}" head="${HEAD_SHA:-HEAD}"
  if [[ -z "$base" || "$base" =~ ^0+$ ]]; then all_unit_ids; return; fi
  local changed
  if ! changed="$(git -C "$ROOT" diff --name-only "$base..$head" 2>/dev/null)"; then ordered_units "$all_ids" "$dependencies"; return; fi
  [[ -n "$changed" ]] || die 'affected scope has no changed files'
  if grep -q '^\.github/' <<<"$changed"; then ordered_units "$all_ids" "$dependencies"; return; fi
  declare -A selected=()
  watch="$(watch_rows)" || die 'failed to parse watch paths'
  local file id pattern matched
  while IFS= read -r file; do
    [[ -z "$file" ]] && continue
    matched=false
    while IFS=$'\t' read -r id pattern; do
      if matches_pattern "$file" "$pattern"; then selected["$id"]=1; matched=true; fi
    done <<< "$watch"
    if [[ "$matched" == false ]]; then ordered_units "$all_ids" "$dependencies"; return; fi
  done <<<"$changed"
  local expanded=true owner dependency
  local dependency_rows="$dependencies"
  while [[ "$expanded" == true ]]; do
    expanded=false
    while IFS=$'\t' read -r owner dependency; do
      if [[ -n "${selected[$owner]:-}" && -z "${selected[$dependency]:-}" ]]; then
        selected["$dependency"]=1
        expanded=true
      elif [[ -n "${selected[$dependency]:-}" && -z "${selected[$owner]:-}" ]]; then
        selected["$owner"]=1
        expanded=true
      fi
    done <<< "$dependency_rows"
  done
  selected_rows=""
  while IFS= read -r id; do
    [[ -n "${selected[$id]:-}" ]] || continue
    selected_rows+="$id"$'\n'
  done <<< "$all_ids"
  ordered_units "$selected_rows" "$dependencies"
}

ordered_units() {
  local selected_rows="$1" dependency_rows="$2" id owner dependency ready progress emitted=0 total=0
  declare -A selected=() finished=()
  while IFS= read -r id; do
    [[ -n "$id" ]] || continue
    selected["$id"]=1
    total=$((total + 1))
  done <<< "$selected_rows"
  while (( emitted < total )); do
    progress=false
    while IFS= read -r id; do
      [[ -n "${selected[$id]:-}" && -z "${finished[$id]:-}" ]] || continue
      ready=true
      while IFS=$'\t' read -r owner dependency; do
        [[ "$owner" == "$id" && -n "${selected[$dependency]:-}" ]] || continue
        if [[ -z "${finished[$dependency]:-}" ]]; then ready=false; break; fi
      done <<< "$dependency_rows"
      [[ "$ready" == true ]] || continue
      printf '%s\n' "$id"
      finished["$id"]=1
      emitted=$((emitted + 1))
      progress=true
    done <<< "$selected_rows"
    [[ "$progress" == true ]] || die 'dependency graph contains a cycle or invalid ordering'
  done
}

commands_for_unit() {
  local wanted_id="$1" field="$2"
  toml_array_rows "$field" | awk -F '\t' -v wanted="$wanted_id" '
    $1 == wanted {
      sub(/^[^\t]*\t/, "")
      print
    }
  '
}

scope_for_event() {
  case "${EVENT_NAME:-}" in
    push|workflow_dispatch|schedule)
      [[ "${CI_SCOPE_OVERRIDE:-full}" == full ]] || die 'trusted events require full scope'
      printf 'full\n'
      ;;
    pull_request|merge_group)
      if [[ -n "${CI_SCOPE_OVERRIDE:-}" ]]; then
        [[ "$CI_SCOPE_OVERRIDE" == affected || "$CI_SCOPE_OVERRIDE" == full ]] || die "unsupported CI_SCOPE_OVERRIDE: $CI_SCOPE_OVERRIDE"
        printf '%s\n' "$CI_SCOPE_OVERRIDE"
      else
        printf 'affected\n'
      fi
      ;;
    '')
      [[ -z "${CI_SCOPE_OVERRIDE:-}" || "$CI_SCOPE_OVERRIDE" == affected || "$CI_SCOPE_OVERRIDE" == full ]] || die "unsupported CI_SCOPE_OVERRIDE: $CI_SCOPE_OVERRIDE"
      printf '%s\n' "${CI_SCOPE_OVERRIDE:-full}"
      ;;
    *)
      printf 'full\n'
      ;;
  esac
}

plan() {
  validate_config
  local scope; scope="$(scope_for_event)"
  if [[ -n "${GITHUB_OUTPUT:-}" ]]; then printf 'scope=%s\n' "$scope" >>"$GITHUB_OUTPUT"; fi
  printf 'scope=%s\n' "$scope"
}

run_unit() {
  local id="$1" field="$2" command commands
  commands="$(commands_for_unit "$id" "$field")" || die "failed to parse $field for $id"
  [[ -n "$commands" ]] || die "unit has no $field: $id"
  while IFS= read -r command; do
    [[ -z "$command" ]] && continue
    printf '::group::%s: %s\n' "$id" "$command"
    bash -euo pipefail -c "$command"
    printf '::endgroup::\n'
  done <<< "$commands"
}

run_tests_per_crate() {
  local manifest lock_args=()
  [[ -f "$ROOT/Cargo.lock" ]] && lock_args+=(--locked)
  cd -- "$ROOT"
  while IFS= read -r -d '' manifest; do
    grep -q '^\[package\][[:space:]]*$' "$manifest" || continue
    printf '::group::cargo tests: %s\n' "$manifest"
    if grep -q 'cargo-nextest-policy' "$CONFIG"; then
      cargo nextest run "${lock_args[@]}" --all-features --manifest-path "$manifest"
    else
      cargo test "${lock_args[@]}" --all-features --manifest-path "$manifest"
    fi
    printf '::endgroup::\n'
  done < <(
    find . \
      \( -path './.git' -o -path './.git/*' -o -path './target' -o -path './target/*' \) -prune \
      -o -type f -name Cargo.toml -print0
  )
}

run_units() {
  local scope="$1" id field
  validate_config
  [[ "$scope" == affected || "$scope" == full ]] || die "unsupported CI scope: $scope"
  case "${EVENT_NAME:-}" in
    push|workflow_dispatch|schedule)
      [[ "$scope" == full ]] || die 'trusted events require full scope'
      ;;
  esac
  field=full_commands; [[ "$scope" == affected ]] && field=pr_commands
  local selected
  if [[ -n "${CI_UNIT_ID:-}" ]]; then
    all_unit_ids | grep -Fxq "$CI_UNIT_ID" || die "unknown CI_UNIT_ID: $CI_UNIT_ID"
    if [[ "$scope" == full ]]; then
      selected="$CI_UNIT_ID"
    else
      selected="$(selected_units "$scope" | grep -Fx "$CI_UNIT_ID" || true)"
    fi
  else
    selected="$(selected_units "$scope")" || die 'failed to select units'
  fi
  local dependencies
  dependencies="$(depends_on_rows)" || die 'failed to parse unit dependencies'
  declare -A pending=() finished=()
  local remaining=0
  while IFS= read -r id; do
    [[ -n "$id" ]] || continue
    pending["$id"]=1
    remaining=$((remaining + 1))
  done <<< "$selected"

  # Execute independent units in parallel, one dependency layer at a time.
  # This gives workspace crates and unrelated project units fan-out without
  # weakening the declared dependency order.
  while (( remaining > 0 )); do
    local ready=() owner dependency ready_for
    while IFS= read -r id; do
      [[ -n "${pending[$id]:-}" && -z "${finished[$id]:-}" ]] || continue
      ready_for=true
      while IFS=$'\t' read -r owner dependency; do
        [[ "$owner" == "$id" && -n "${pending[$dependency]:-}" ]] || continue
        if [[ -z "${finished[$dependency]:-}" ]]; then
          ready_for=false
          break
        fi
      done <<< "$dependencies"
      [[ "$ready_for" == true ]] && ready+=("$id")
    done <<< "$selected"
    ((${#ready[@]} > 0)) || die 'dependency graph contains a cycle or invalid ordering'

    local pids=() pid status=0
    for id in "${ready[@]}"; do
      run_unit "$id" "$field" &
      pids+=("$!")
    done
    for pid in "${pids[@]}"; do
      if ! wait "$pid"; then status=1; fi
    done
    ((status == 0)) || return "$status"
    for id in "${ready[@]}"; do finished["$id"]=1; done
    remaining=$((remaining - ${#ready[@]}))
  done
}

case "${1:-}" in
  plan) plan ;;
  test-crates) run_tests_per_crate ;;
  run) [[ "${2:-}" == --scope && -n "${3:-}" ]] || die 'usage: run.sh run --scope affected|full'; run_units "$3" ;;
  *) die 'usage: run.sh plan | run.sh test-crates | run.sh run --scope affected|full' ;;
esac
