//! The generator-owned agent files: every full render — schema-1 and
//! schema-2, even for minimal repositories — emits `.github/AGENTS.md` with
//! fixed bytes plus the relative `.github/CLAUDE.md -> AGENTS.md` symlink,
//! and repeating generation is a byte-identical no-op.

#![expect(
    clippy::unwrap_used,
    reason = "a test whose setup fails should panic loudly"
)]
#![expect(
    clippy::expect_used,
    reason = "a test whose setup fails should panic loudly"
)]

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// The exact `.github/AGENTS.md` bytes, transcribed from the increment
/// contract: fixed text with a trailing newline, identical for every
/// repository and both pipelines.
const EXPECTED_AGENTS_MD: &str = "# Generated files\n\
    \n\
    Everything under `.github` is generated by [velnor-workflow](https://github.com/tailrocks/velnor/tree/main/crates/velnor-workflow).\n\
    \n\
    Never hand-edit this directory. Changes to generated behavior require a Velnor PR: first research, analyze, and independently verify a generic solution, never a repository-specific workaround. Keep generation inputs outside `.github`, then regenerate. Root `AGENTS.md` rules still apply.\n";

struct Generated {
    output: PathBuf,
}

fn unique_dir(name: &str) -> PathBuf {
    static NEXT: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);
    let id = NEXT.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    let root = std::env::temp_dir().join(format!(
        "velnor-agent-files-{name}-{}-{id}",
        std::process::id()
    ));
    let _ = fs::remove_dir_all(&root);
    fs::create_dir_all(&root).unwrap();
    root
}

fn copy_tree(source: &Path, destination: &Path) {
    fs::create_dir_all(destination).unwrap();
    for entry in fs::read_dir(source).unwrap() {
        let entry = entry.unwrap();
        let target = destination.join(entry.file_name());
        if entry.file_type().unwrap().is_dir() {
            copy_tree(&entry.path(), &target);
        } else {
            fs::copy(entry.path(), &target).unwrap();
        }
    }
}

/// The minimal-shape fixture: a single Rust crate, no generation config.
fn minimal_root(name: &str) -> PathBuf {
    let source = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/minimal-rust");
    let root = unique_dir(name).join("fixture");
    copy_tree(&source, &root);
    root
}

fn generate(root: &Path, extra: &[&str]) -> Generated {
    let output = root.parent().unwrap().join(format!(
        "{}-out",
        root.file_name().and_then(|name| name.to_str()).unwrap()
    ));
    let _ = fs::remove_dir_all(&output);
    regenerate_into(&output, root, extra);
    Generated { output }
}

/// Regenerate into an existing output tree without `--force`: a current tree
/// is a no-op success, so this proves repeat generation has no conflicts.
fn regenerate_into(output: &Path, root: &Path, extra: &[&str]) {
    let mut args = vec!["--plain", "--default-branch", "main", "--output"];
    let output = output.to_str().unwrap();
    args.push(output);
    args.extend_from_slice(extra);
    args.push(root.to_str().unwrap());
    let outcome = Command::new(env!("CARGO_BIN_EXE_velnor-workflow"))
        .args(&args)
        .output()
        .expect("run velnor-workflow");
    assert!(
        outcome.status.success(),
        "generation failed:\n{}",
        String::from_utf8_lossy(&outcome.stderr)
    );
}

/// A retargeted generator-owned link must fail closed even under `--force`:
/// force bypasses the conflicts guard, never the ownership proof.
fn assert_retargeted_link_is_refused(root: &Path, output: &Path, extra: &[&str]) {
    let link = output.join(".github/CLAUDE.md");
    fs::remove_file(&link).unwrap();
    #[cfg(unix)]
    std::os::unix::fs::symlink("/tmp/velnor-agent-files-evil", &link).unwrap();
    #[cfg(windows)]
    std::os::windows::fs::symlink_file("velnor-agent-files-evil", &link).unwrap();
    let mut args = vec!["--plain", "--force", "--default-branch", "main", "--output"];
    args.push(output.to_str().unwrap());
    args.extend_from_slice(extra);
    args.push(root.to_str().unwrap());
    let outcome = Command::new(env!("CARGO_BIN_EXE_velnor-workflow"))
        .args(&args)
        .output()
        .expect("run velnor-workflow");
    assert!(
        !outcome.status.success(),
        "a retargeted generator-owned link must fail closed"
    );
    let stderr = String::from_utf8_lossy(&outcome.stderr);
    assert!(
        stderr.contains("manually modified generator symlink"),
        "refusal must name the modified link: {stderr}"
    );
    assert!(
        fs::symlink_metadata(&link)
            .unwrap()
            .file_type()
            .is_symlink(),
        "the refused run must leave the link untouched"
    );
}

fn check(root: &Path, output: &Path, extra: &[&str]) {
    let mut args = vec!["--plain", "--check", "--default-branch", "main", "--output"];
    args.push(output.to_str().unwrap());
    args.extend_from_slice(extra);
    args.push(root.to_str().unwrap());
    let outcome = Command::new(env!("CARGO_BIN_EXE_velnor-workflow"))
        .args(&args)
        .output()
        .expect("run velnor-workflow --check");
    assert!(
        outcome.status.success(),
        "check after generate failed:\n{}",
        String::from_utf8_lossy(&outcome.stderr)
    );
}

/// Every output-tree byte plus every symlink target, so a repeat-generation
/// comparison proves a true no-op instead of a quiet rewrite.
fn snapshot_tree(output: &Path) -> BTreeMap<PathBuf, Vec<u8>> {
    fn visit(base: &Path, directory: &Path, snapshot: &mut BTreeMap<PathBuf, Vec<u8>>) {
        let mut entries: Vec<PathBuf> = fs::read_dir(directory)
            .unwrap()
            .map(|entry| entry.unwrap().path())
            .collect();
        entries.sort();
        for path in entries {
            let relative = path.strip_prefix(base).unwrap().to_path_buf();
            let metadata = fs::symlink_metadata(&path).unwrap();
            if metadata.file_type().is_symlink() {
                let mut record = b"link:".to_vec();
                record.extend(fs::read_link(&path).unwrap().as_os_str().as_encoded_bytes());
                snapshot.insert(relative, record);
            } else if metadata.is_dir() {
                visit(base, &path, snapshot);
            } else {
                let mut record = b"file:".to_vec();
                record.extend(fs::read(&path).unwrap());
                snapshot.insert(relative, record);
            }
        }
    }

    let mut snapshot = BTreeMap::new();
    visit(output, output, &mut snapshot);
    snapshot
}

fn assert_agent_files(output: &Path) {
    let agents = output.join(".github/AGENTS.md");
    let link = output.join(".github/CLAUDE.md");
    let agents_metadata = fs::symlink_metadata(&agents).unwrap();
    assert!(
        agents_metadata.file_type().is_file() && !agents_metadata.file_type().is_symlink(),
        ".github/AGENTS.md must be a regular file"
    );
    assert_eq!(
        fs::read_to_string(&agents).unwrap(),
        EXPECTED_AGENTS_MD,
        ".github/AGENTS.md bytes differ from the contract"
    );
    assert!(
        fs::symlink_metadata(&link)
            .unwrap()
            .file_type()
            .is_symlink(),
        ".github/CLAUDE.md must be a symlink"
    );
    assert_eq!(
        fs::read_link(&link).unwrap(),
        PathBuf::from("AGENTS.md"),
        ".github/CLAUDE.md must point at the relative AGENTS.md"
    );
    let state =
        fs::read_to_string(output.join(".github/ci/.github-actions-generator-state")).unwrap();
    assert!(
        state.contains(".github/AGENTS.md\t"),
        "ownership state must record .github/AGENTS.md"
    );
    assert!(
        state.contains(".github/CLAUDE.md\t"),
        "ownership state must record .github/CLAUDE.md"
    );
}

fn write_schema1_config(root: &Path) {
    let directory = root.join(".github-gen");
    fs::create_dir_all(&directory).unwrap();
    fs::write(
        directory.join("velnor-workflow.toml"),
        "schema = 1\n\
         \n\
         [generator]\n\
         repository = \"example/minimal\"\n\
         \n\
         [workflow]\n\
         runners = \"github\"\n\
         github_runner = \"ubuntu-24.04\"\n",
    )
    .unwrap();
}

fn write_schema2_config(root: &Path) {
    let directory = root.join(".github-gen");
    fs::create_dir_all(&directory).unwrap();
    fs::write(
        directory.join("velnor-workflow.toml"),
        "schema = 2\n\
         \n\
         [generator]\n\
         repository = \"example/minimal\"\n\
         \n\
         [workflow]\n\
         providers = [\"github-hosted\"]\n\
         automatic_providers = [\"github-hosted\"]\n\
         \n\
         [workflow.selectors.github-hosted]\n\
         runs_on = [\"ubuntu-24.04\"]\n",
    )
    .unwrap();
}

#[test]
fn v1_minimal_repo_emits_agent_files_and_regen_is_noop() {
    let root = minimal_root("v1-minimal");
    // The minimal shape has no self-hosted labels, so the schema-1 config
    // renders the hosted lane only; `--check` re-renders from this config.
    write_schema1_config(&root);
    let extra: [&str; 0] = [];
    let generated = generate(&root, &extra);
    assert_agent_files(&generated.output);
    let before = snapshot_tree(&generated.output);
    regenerate_into(&generated.output, &root, &extra);
    assert_eq!(
        snapshot_tree(&generated.output),
        before,
        "repeat generation must leave every byte and link untouched"
    );
    check(&root, &generated.output, &extra);
    assert_retargeted_link_is_refused(&root, &generated.output, &extra);
}

#[test]
fn s2_minimal_repo_emits_agent_files_and_regen_is_noop() {
    let root = minimal_root("s2-minimal");
    write_schema2_config(&root);
    let extra: [&str; 0] = [];
    let generated = generate(&root, &extra);
    assert_agent_files(&generated.output);
    let before = snapshot_tree(&generated.output);
    regenerate_into(&generated.output, &root, &extra);
    assert_eq!(
        snapshot_tree(&generated.output),
        before,
        "repeat generation must leave every byte and link untouched"
    );
    check(&root, &generated.output, &extra);
    assert_retargeted_link_is_refused(&root, &generated.output, &extra);
}

#[test]
fn v1_richer_repo_emits_identical_agent_files() {
    let source = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/synthetic-workspace");
    let root = unique_dir("v1-rich").join("fixture");
    copy_tree(&source, &root);
    let extra = ["--runners", "both"];
    let generated = generate(&root, &extra);
    assert_agent_files(&generated.output);
}

#[test]
fn s2_richer_repo_emits_identical_agent_files() {
    let source = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures-s2/polyglot");
    let root = unique_dir("s2-rich").join("fixture");
    copy_tree(&source, &root);
    write_schema2_config(&root);
    let extra: [&str; 0] = [];
    let generated = generate(&root, &extra);
    assert_agent_files(&generated.output);
}
