#!/usr/bin/env bash
# Clean-room workflow regeneration: wipe legacy CI state, regenerate from velnor.
# Usage: clean-room-regen.sh owner/repo [--merge] [--keep-config]
set -euo pipefail

export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:${PATH:-}"
unset MISE_SHELL 2>/dev/null || true

REPO_SLUG="${1:?owner/repo required}"
MERGE="${2:-}"
KEEP_CONFIG="${3:-}"
OWNER="${REPO_SLUG%%/*}"
NAME="${REPO_SLUG##*/}"
VELNOR_ROOT="${VELNOR_ROOT:-/Users/donbeave/Projects/tailrocks/velnor-project/velnor}"
VELNOR_BIN="${VELNOR_BIN:-$VELNOR_ROOT/target/release/velnor-workflow}"
WORK_ROOT="${WORK_ROOT:-/tmp/velnor-clean-room}"
REPO_DIR="${REPO_DIR:-$WORK_ROOT/$OWNER/$NAME}"
BRANCH="${BRANCH:-velnor-legacy-debt-$(date +%Y%m%d)}"
GENERATOR_REV="${GENERATOR_REV:-1279c4f92c97b75dc4cc627f122e119f8a5eae16}"

mkdir -p "$WORK_ROOT/$OWNER"
if [[ -d "$REPO_DIR/.git" ]]; then
  /usr/bin/git -C "$REPO_DIR" fetch origin
else
  /usr/local/bin/gh repo clone "$REPO_SLUG" "$REPO_DIR" 2>/dev/null || \
    /opt/homebrew/bin/gh repo clone "$REPO_SLUG" "$REPO_DIR"
fi

DEFAULT_BRANCH="$(/usr/local/bin/gh api "repos/$REPO_SLUG" --jq '.default_branch' 2>/dev/null || \
  /opt/homebrew/bin/gh api "repos/$REPO_SLUG" --jq '.default_branch')"
/usr/bin/git -C "$REPO_DIR" checkout "$DEFAULT_BRANCH"
/usr/bin/git -C "$REPO_DIR" reset --hard "origin/$DEFAULT_BRANCH"
/usr/bin/git -C "$REPO_DIR" pull --ff-only origin "$DEFAULT_BRANCH" || true

# Remove legacy generator mechanisms unless keeping config
if [[ "$KEEP_CONFIG" != "--keep-config" ]]; then
  /bin/rm -rf "$REPO_DIR/.github-gen/generated-templates" 2>/dev/null || true
  /bin/rm -rf "$REPO_DIR/.github-gen/sources" 2>/dev/null || true
fi

# Strip static_files blocks and legacy velnor-actions-generator artifacts
if [[ -f "$REPO_DIR/.github-gen/velnor-workflow.toml" ]]; then
  /usr/bin/awk '
    /^\[\[static_files\]\]/ { skip=1; next }
    skip && /^$/ { skip=0; next }
    skip && /^\[\[/ { skip=0 }
    skip { next }
    { print }
  ' "$REPO_DIR/.github-gen/velnor-workflow.toml" > "$REPO_DIR/.github-gen/velnor-workflow.toml.tmp"
  /bin/mv "$REPO_DIR/.github-gen/velnor-workflow.toml.tmp" "$REPO_DIR/.github-gen/velnor-workflow.toml"
fi

/bin/rm -f "$REPO_DIR/.github/actions/report-velnor-ci-outcomes/action.yml" 2>/dev/null || true
/bin/rm -rf "$REPO_DIR/.github/actions/report-velnor-ci-outcomes" 2>/dev/null || true
/bin/rm -f "$REPO_DIR/.github/ci/.github-actions-generator-state" 2>/dev/null || true
/bin/rm -f "$REPO_DIR/.github/ci/project.toml" 2>/dev/null || true

# Schemalane-style velnor-actions-generator leftovers
if /usr/bin/grep -q "Generated by velnor-actions-generator" "$REPO_DIR/.alint.yml" 2>/dev/null; then
  /bin/rm -f "$REPO_DIR/.alint.yml"
fi
if /usr/bin/grep -q "Generated by velnor-actions-generator" "$REPO_DIR/.ignore" 2>/dev/null; then
  /bin/rm -f "$REPO_DIR/.ignore"
fi

# Ensure generator revision pin
if [[ ! -f "$REPO_DIR/.github-gen/velnor-workflow.toml" ]]; then
  /bin/mkdir -p "$REPO_DIR/.github-gen"
  /usr/bin/printf '%s\n' \
    "schema = 1" "" \
    "[generator]" \
    "repository = \"$REPO_SLUG\"" \
    "revision = \"$GENERATOR_REV\"" "" \
    "[workflow]" \
    "runners = \"both\"" \
    "automatic_lanes = \"github\"" \
    "default_dispatch_runner = \"github\"" \
    "github_runner = \"ubuntu-24.04\"" \
    "velnor_labels = [\"self-hosted\", \"velnor-target-mvp\"]" \
    "default_branch = \"$DEFAULT_BRANCH\"" \
    > "$REPO_DIR/.github-gen/velnor-workflow.toml"
else
  if /usr/bin/grep -q '^revision = ' "$REPO_DIR/.github-gen/velnor-workflow.toml"; then
    /usr/bin/sed -i '' "s/^revision = .*/revision = \"$GENERATOR_REV\"/" "$REPO_DIR/.github-gen/velnor-workflow.toml"
  else
    /usr/bin/sed -i '' "/^\[generator\]/a\\
revision = \"$GENERATOR_REV\"
" "$REPO_DIR/.github-gen/velnor-workflow.toml"
  fi
fi

# Regenerate
"$VELNOR_BIN" "$REPO_DIR" --plain --force --default-branch "$DEFAULT_BRANCH"
"$VELNOR_BIN" "$REPO_DIR" --plain --check --default-branch "$DEFAULT_BRANCH"

/usr/bin/git -C "$REPO_DIR" checkout -B "$BRANCH"
/usr/bin/git -C "$REPO_DIR" add -A
if /usr/bin/git -C "$REPO_DIR" diff --cached --quiet; then
  echo "No changes for $REPO_SLUG"
  exit 0
fi

/usr/bin/git -C "$REPO_DIR" commit -s -m "$(/usr/bin/printf '%s\n' \
  "chore(ci): clean-room velnor-workflow regeneration" \
  "" \
  "Remove legacy static_files and velnor-actions-generator artifacts;" \
  "regenerate from tailrocks/velnor@${GENERATOR_REV}." \
  "" \
  "Generator-only workflow output.")"

/usr/bin/git -C "$REPO_DIR" push -u origin "$BRANCH" --force

GH=/usr/local/bin/gh
command -v "$GH" >/dev/null 2>&1 || GH=/opt/homebrew/bin/gh
PR_URL="$("$GH" pr create --repo "$REPO_SLUG" --head "$BRANCH" --base "$DEFAULT_BRANCH" \
  --title "Clean-room velnor-workflow regeneration" \
  --body "Removes legacy \`static_files\` / velnor-actions-generator debt and regenerates from \`tailrocks/velnor@${GENERATOR_REV}\`." \
  2>/dev/null || "$GH" pr list --repo "$REPO_SLUG" --head "$BRANCH" --json url -q '.[0].url')"

echo "PR: $PR_URL"

if [[ "$MERGE" == "--merge" ]]; then
  "$GH" pr merge "$PR_URL" --squash --admin --delete-branch 2>/dev/null || \
    "$GH" pr merge "$PR_URL" --squash --delete-branch
  echo "Merged: $PR_URL"
fi
