//! Maintainer-only org-JIT fleet policy model (Plan 039 Steps 1–2).
//!
//! Deterministic generation surface: strict validation, canonical JSON,
//! sha256 digests, and the release-ref ledger schema. `generate` is fully
//! offline: it reads the release-ref ledger and emits byte-stable per-org
//! policy JSON (see [`generate_policies_from_ledger`]). `plan` prints a
//! desired-policy summary offline. `audit` and `apply` reach live GitHub
//! runner-group state through [`crate::fleet_policy_client::FleetGateway`]
//! (`ReqwestFleetHttp`); apply stays manual and digest-gated.

use anyhow::{bail, Context, Result};
use clap::{Args, Subcommand};
use serde::{Deserialize, Serialize};
use sha2::{Digest as ShaDigest, Sha256};
use std::{
    collections::{BTreeMap, BTreeSet},
    fmt, fs,
    path::{Path, PathBuf},
};
use time::{Date, Month};

use crate::fleet_policy_client::{
    FleetGateway, ReqwestFleetHttp, RetryPolicy, DEFAULT_GITHUB_API_URL,
};

/// Version of the fleet-policy contract this module implements.
pub const POLICY_CONTRACT_VERSION: &str = "1";
/// Version of the deterministic generator producing canonical bytes.
pub const GENERATOR_VERSION: &str = "fleet-policy-gen/1";
/// Schema version of the release-ref ledger.
pub const RELEASE_REF_LEDGER_SCHEMA_VERSION: i64 = 1;
/// Required runner selection label (leaf Step 1).
pub const REQUIRED_RUNNER_LABEL: &str = "velnor-target-mvp";
/// Required non-default runner group name.
pub const REQUIRED_GROUP_NAME: &str = "velnor-trusted";
/// GitHub REST API version targeted by future live operations.
#[allow(dead_code)]
pub const GITHUB_API_VERSION: &str = "2026-03-10";

const WORKFLOW_DIR_PREFIX: &str = ".github/workflows/";
const REFS_HEADS_PREFIX: &str = "refs/heads/";
const REFS_TAGS_PREFIX: &str = "refs/tags/";
const FULL_SHA_LEN: usize = 40;
const WILDCARDS: [char; 2] = ['*', '?'];

// ---------------------------------------------------------------------------
// Policy model
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum GroupVisibility {
    Selected,
}

impl fmt::Display for GroupVisibility {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            GroupVisibility::Selected => write!(f, "selected"),
        }
    }
}

/// One admitted workflow identity: `<owner>/<repo>/.github/workflows/<file>@<qualified ref>`.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct WorkflowIdentity {
    /// Full path including `owner/repo` prefix.
    pub path: String,
    /// Qualified `refs/heads/...`, exact `refs/tags/...`, or full 40-char SHA.
    #[serde(rename = "ref")]
    pub git_ref: String,
}

impl WorkflowIdentity {
    pub fn to_selected_string(&self) -> String {
        format!("{}@{}", self.path, self.git_ref)
    }
}

impl fmt::Display for WorkflowIdentity {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.to_selected_string())
    }
}

/// Generated per-organization trusted-group policy (leaf Step 1 fields).
///
/// Field declaration order is the canonical JSON order; vectors must be kept
/// sorted (see [`OrgPolicy::normalized`]) so generated bytes are reproducible.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OrgPolicy {
    pub schema_version: i64,
    pub contract_version: String,
    pub generator_version: String,
    pub organization: String,
    pub group_name: String,
    pub runner_labels: Vec<String>,
    pub visibility: GroupVisibility,
    pub allows_public_repositories: bool,
    pub restricted_to_workflows: bool,
    /// Sorted, duplicate-free `owner/repo` values.
    pub selected_repositories: Vec<String>,
    /// Sorted, duplicate-free workflow identities.
    pub selected_workflows: Vec<WorkflowIdentity>,
}

impl OrgPolicy {
    #[allow(dead_code)]
    pub fn new(organization: impl Into<String>) -> Self {
        Self {
            schema_version: RELEASE_REF_LEDGER_SCHEMA_VERSION,
            contract_version: POLICY_CONTRACT_VERSION.to_owned(),
            generator_version: GENERATOR_VERSION.to_owned(),
            organization: organization.into(),
            group_name: REQUIRED_GROUP_NAME.to_owned(),
            runner_labels: vec![REQUIRED_RUNNER_LABEL.to_owned()],
            visibility: GroupVisibility::Selected,
            allows_public_repositories: true,
            restricted_to_workflows: true,
            selected_repositories: Vec::new(),
            selected_workflows: Vec::new(),
        }
    }

    /// Sort and de-duplicate the mutable entry sets in place.
    #[allow(dead_code)]
    pub fn normalized(mut self) -> Self {
        self.runner_labels = normalize_strings(self.runner_labels);
        self.selected_repositories = normalize_strings(self.selected_repositories);
        let workflows: BTreeSet<WorkflowIdentity> = self.selected_workflows.into_iter().collect();
        self.selected_workflows = workflows.into_iter().collect();
        self
    }

    /// Canonical compact JSON; fails closed on an invalid policy.
    pub fn canonical_json(&self) -> Result<String> {
        validate_policy(self)?;
        serde_json::to_string(self).context("canonical policy JSON serialization")
    }

    /// `sha256:<hex>` over [`Self::canonical_json`] bytes.
    pub fn digest(&self) -> Result<String> {
        let json = self.canonical_json()?;
        Ok(format!("sha256:{}", hex_digest(json.as_bytes())))
    }
}

fn normalize_strings(values: Vec<String>) -> Vec<String> {
    values
        .into_iter()
        .collect::<BTreeSet<_>>()
        .into_iter()
        .collect()
}

fn hex_digest(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    let out = hasher.finalize();
    out.iter().map(|byte| format!("{byte:02x}")).collect()
}

/// Reject a stale reviewed digest against the freshly computed one.
pub fn verify_plan_digest(reported: &str, actual: &str) -> Result<()> {
    if reported == actual {
        return Ok(());
    }
    bail!(
        "field 'plan_digest': reported digest '{reported}' is stale; current policy digest is '{actual}' (re-run plan and re-review)"
    );
}

// ---------------------------------------------------------------------------
// Validation (deterministic messages naming exact field/value)
// ---------------------------------------------------------------------------

pub fn validate_policy(policy: &OrgPolicy) -> Result<()> {
    if policy.schema_version != RELEASE_REF_LEDGER_SCHEMA_VERSION {
        bail!(
            "field 'schema_version': value {} is unsupported; expected {}",
            policy.schema_version,
            RELEASE_REF_LEDGER_SCHEMA_VERSION
        );
    }
    if policy.contract_version != POLICY_CONTRACT_VERSION {
        bail!(
            "field 'contract_version': value '{}' is unsupported; expected '{}'",
            policy.contract_version,
            POLICY_CONTRACT_VERSION
        );
    }
    if policy.generator_version != GENERATOR_VERSION {
        bail!(
            "field 'generator_version': value '{}' is unsupported; expected '{}'",
            policy.generator_version,
            GENERATOR_VERSION
        );
    }
    if policy.organization.trim().is_empty() {
        bail!("field 'organization': value must be a non-empty organization login");
    }
    if policy.group_name != REQUIRED_GROUP_NAME {
        bail!(
            "field 'group_name': value '{}' must equal required non-default group '{}'",
            policy.group_name,
            REQUIRED_GROUP_NAME
        );
    }
    if !policy
        .runner_labels
        .iter()
        .any(|label| label == REQUIRED_RUNNER_LABEL)
    {
        bail!(
            "field 'runner_labels': values {:?} must include required label '{}'",
            policy.runner_labels,
            REQUIRED_RUNNER_LABEL
        );
    }
    if policy.runner_labels != normalize_strings(policy.runner_labels.clone()) {
        bail!(
            "field 'runner_labels': values {:?} must be sorted and duplicate-free",
            policy.runner_labels
        );
    }
    for label in &policy.runner_labels {
        if label.chars().any(|c| WILDCARDS.contains(&c)) {
            bail!("field 'runner_labels': value '{label}' must not contain wildcards");
        }
    }
    if !matches!(policy.visibility, GroupVisibility::Selected) {
        bail!(
            "field 'visibility': value '{}' must be 'selected'",
            policy.visibility
        );
    }
    if !policy.allows_public_repositories {
        bail!("field 'allows_public_repositories': value false must be true");
    }
    if !policy.restricted_to_workflows {
        bail!("field 'restricted_to_workflows': value false must be true");
    }
    if policy.selected_repositories.is_empty() {
        bail!("field 'selected_repositories': value must be non-empty");
    }
    if policy.selected_workflows.is_empty() {
        bail!("field 'selected_workflows': value must be non-empty");
    }
    if policy.selected_repositories != normalize_strings(policy.selected_repositories.clone()) {
        bail!(
            "field 'selected_repositories': values {:?} must be sorted and duplicate-free",
            policy.selected_repositories
        );
    }
    for repository in &policy.selected_repositories {
        ensure_slug("selected_repositories", repository)?;
    }

    let mut seen_paths: BTreeMap<String, String> = BTreeMap::new();
    let mut seen_values: BTreeSet<String> = BTreeSet::new();
    let mut covered_repos: BTreeSet<String> = BTreeSet::new();
    for identity in &policy.selected_workflows {
        let value = identity.to_selected_string();
        if !seen_values.insert(value.clone()) {
            bail!("field 'selected_workflows': duplicate entry '{value}'");
        }
        ensure_no_wildcard("selected_workflows", &value)?;
        ensure_qualified_ref("selected_workflows", &value, &identity.git_ref)?;
        let (owner_repo, _) = split_identity_path("selected_workflows", &value, &identity.path)?;
        if !policy.selected_repositories.contains(&owner_repo) {
            bail!(
                "field 'selected_workflows': entry '{value}' references repository '{owner_repo}' absent from field 'selected_repositories'"
            );
        }
        if let Some(prior_ref) = seen_paths.get(&identity.path) {
            if prior_ref != &identity.git_ref {
                bail!(
                    "field 'selected_workflows': contradictory entries for workflow path '{}': refs '{prior_ref}' and '{}'",
                    identity.path,
                    identity.git_ref
                );
            }
        }
        seen_paths.insert(identity.path.clone(), identity.git_ref.clone());
        covered_repos.insert(owner_repo);
    }
    if policy.selected_workflows != {
        let mut workflows = policy.selected_workflows.clone();
        workflows.sort();
        workflows
    } {
        bail!(
            "field 'selected_workflows': values must be sorted and duplicate-free; got {:?}",
            policy
                .selected_workflows
                .iter()
                .map(WorkflowIdentity::to_selected_string)
                .collect::<Vec<_>>()
        );
    }
    for repository in &policy.selected_repositories {
        if !covered_repos.contains(repository) {
            bail!(
                "field 'selected_repositories': value '{repository}' has no 'selected_workflows' entry (extra selection)"
            );
        }
    }
    Ok(())
}

fn ensure_slug(field: &str, value: &str) -> Result<()> {
    let invalid = |message: String| anyhow::anyhow!("field '{field}': {message}");
    let mut parts = value.splitn(2, '/');
    let (owner, repo) = match (parts.next(), parts.next()) {
        (Some(owner), Some(repo)) if !repo.contains('/') => (owner, repo),
        _ => return Err(invalid(format!("value '{value}' must be 'owner/repo'"))),
    };
    let slug_ok = |part: &str| {
        !part.is_empty()
            && part
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '.' | '_'))
    };
    if !slug_ok(owner) || !slug_ok(repo) {
        return Err(invalid(format!(
            "value '{value}' is not a valid owner/repo slug"
        )));
    }
    Ok(())
}

/// Split `owner/repo/.github/workflows/file.(yml|yaml)` into `(owner/repo, file)`.
fn split_identity_path(field: &str, value: &str, path: &str) -> Result<(String, String)> {
    let segments: Vec<&str> = path.split('/').collect();
    let shape = "owner/repo/.github/workflows/file.yml";
    if segments.len() < 5 {
        return Err(anyhow::anyhow!(
            "field '{field}': entry '{value}' has path '{path}'; expected '{shape}'"
        ));
    }
    let owner = segments[0];
    let repo = segments[1];
    if segments[2] != ".github" || segments[3] != "workflows" {
        return Err(anyhow::anyhow!(
            "field '{field}': entry '{value}' has path '{path}'; expected '{shape}'"
        ));
    }
    let file = segments[4..].join("/");
    if !file.ends_with(".yml") && !file.ends_with(".yaml") {
        return Err(anyhow::anyhow!(
            "field '{field}': entry '{value}' workflow file '{file}' must end in .yml or .yaml"
        ));
    }
    Ok((format!("{owner}/{repo}"), file))
}

fn ensure_no_wildcard(field: &str, value: &str) -> Result<()> {
    if value.chars().any(|c| WILDCARDS.contains(&c)) {
        bail!("field '{field}': value '{value}' must not contain wildcards");
    }
    Ok(())
}

/// Validate a `YYYY-MM-DD` calendar date (real month/day bounds).
fn ensure_calendar_date(value: &str) -> std::result::Result<(), String> {
    let shape = "must be a real YYYY-MM-DD date";
    let mut parts = value.splitn(3, '-');
    let (year, month, day) = match (parts.next(), parts.next(), parts.next()) {
        (Some(y), Some(m), Some(d)) if y.len() == 4 && m.len() == 2 && d.len() == 2 => (y, m, d),
        _ => return Err(shape.to_owned()),
    };
    let year: i32 = year.parse().map_err(|_| shape)?;
    let month: u8 = month.parse().map_err(|_| shape)?;
    let day: u8 = day.parse().map_err(|_| shape)?;
    let month = Month::try_from(month).map_err(|_| shape)?;
    Date::from_calendar_date(year, month, day).map_err(|_| shape)?;
    Ok(())
}

fn ensure_qualified_ref(field: &str, value: &str, git_ref: &str) -> Result<()> {
    if git_ref.starts_with(REFS_HEADS_PREFIX) && git_ref.len() > REFS_HEADS_PREFIX.len() {
        return Ok(());
    }
    if git_ref.starts_with(REFS_TAGS_PREFIX) && git_ref.len() > REFS_TAGS_PREFIX.len() {
        return Ok(());
    }
    if git_ref.len() == FULL_SHA_LEN && git_ref.chars().all(|c| c.is_ascii_hexdigit()) {
        return Ok(());
    }
    bail!(
        "field '{field}': entry '{value}' has unqualified ref '{git_ref}'; use '{REFS_HEADS_PREFIX}...', exact '{REFS_TAGS_PREFIX}...', or a full {FULL_SHA_LEN}-character SHA"
    );
}

// ---------------------------------------------------------------------------
// Release-ref ledger
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ReviewState {
    Approved,
    SeedPendingReview,
    Expired,
}

/// One approved release/default-branch workflow admission record.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ReleaseRefEntry {
    pub owner: String,
    pub repository: String,
    pub workflow_path: String,
    pub git_ref: String,
    pub admission_reason: String,
    pub approving_change: String,
    pub review_state: ReviewState,
    /// Optional review-by date (`YYYY-MM-DD`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expiry: Option<String>,
}

/// Versioned release-ref ledger (leaf Step 1; generator-owned, audit-ci-validated).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ReleaseRefLedger {
    pub schema_version: i64,
    pub entries: Vec<ReleaseRefEntry>,
}

impl ReleaseRefLedger {
    pub fn load(path: &Path) -> Result<Self> {
        let raw = fs::read_to_string(path)
            .with_context(|| format!("reading release-ref ledger {}", path.display()))?;
        let ledger: Self = toml::from_str(&raw)
            .with_context(|| format!("parsing release-ref ledger {}", path.display()))?;
        validate_ledger(&ledger)?;
        Ok(ledger)
    }

    /// Ledger entries whose review state admits them to generated policy.
    #[allow(dead_code)]
    pub fn approved_workflow_identities(&self) -> Result<Vec<WorkflowIdentity>> {
        let mut identities = Vec::new();
        for entry in &self.entries {
            if !matches!(entry.review_state, ReviewState::Approved) {
                continue;
            }
            identities.push(WorkflowIdentity {
                path: format!(
                    "{}/{}/{}",
                    entry.owner, entry.repository, entry.workflow_path
                ),
                git_ref: entry.git_ref.clone(),
            });
        }
        identities.sort();
        Ok(identities)
    }
}

pub fn validate_ledger(ledger: &ReleaseRefLedger) -> Result<()> {
    if ledger.schema_version != RELEASE_REF_LEDGER_SCHEMA_VERSION {
        bail!(
            "field 'schema_version': value {} is unsupported; expected {}",
            ledger.schema_version,
            RELEASE_REF_LEDGER_SCHEMA_VERSION
        );
    }
    if ledger.entries.is_empty() {
        bail!("field 'entries': value must be non-empty");
    }
    let mut seen_exact: BTreeSet<String> = BTreeSet::new();
    let mut seen_paths: BTreeMap<(String, String, String), String> = BTreeMap::new();
    for entry in &ledger.entries {
        let slug = format!("{}/{}", entry.owner, entry.repository);
        ensure_slug("entries.owner/repository", &slug)?;
        if !entry.workflow_path.starts_with(WORKFLOW_DIR_PREFIX) {
            bail!(
                "field 'entries.workflow_path': value '{}' must start with '{WORKFLOW_DIR_PREFIX}'",
                entry.workflow_path
            );
        }
        ensure_no_wildcard("entries.workflow_path", &entry.workflow_path)?;
        if !entry.workflow_path.ends_with(".yml") && !entry.workflow_path.ends_with(".yaml") {
            bail!(
                "field 'entries.workflow_path': value '{}' must end in .yml or .yaml",
                entry.workflow_path
            );
        }
        let identity = format!("{slug}/{}@{}", entry.workflow_path, entry.git_ref);
        ensure_qualified_ref("entries.git_ref", &identity, &entry.git_ref)?;
        if entry.admission_reason.trim().is_empty() {
            bail!(
                "field 'entries': admission_reason for '{slug}/{}' must be non-empty",
                entry.workflow_path
            );
        }
        if entry.approving_change.trim().is_empty() {
            bail!(
                "field 'entries': approving_change for '{slug}/{}' must be non-empty",
                entry.workflow_path
            );
        }
        if matches!(entry.review_state, ReviewState::Expired) {
            bail!(
                "field 'entries': review_state 'expired' for '{slug}/{}' rejects admission; remove or re-approve the entry",
                entry.workflow_path
            );
        }
        if let Some(expiry) = &entry.expiry {
            if let Err(message) = ensure_calendar_date(expiry) {
                bail!(
                    "field 'entries.expiry': value '{expiry}' for '{slug}/{}' {message}",
                    entry.workflow_path
                );
            }
        }
        let exact = format!("{slug}/{}@{}", entry.workflow_path, entry.git_ref);
        if !seen_exact.insert(exact.clone()) {
            bail!("field 'entries': duplicate entry '{exact}'");
        }
        let key = (
            entry.owner.clone(),
            entry.repository.clone(),
            entry.workflow_path.clone(),
        );
        if let Some(prior_ref) = seen_paths.get(&key) {
            bail!(
                "field 'entries': contradictory entries for '{slug}/{}': git_ref '{prior_ref}' and '{}'",
                entry.workflow_path,
                entry.git_ref
            );
        }
        seen_paths.insert(key, entry.git_ref.clone());
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Observed-state seam (fake implementations only until the live client lands)
// ---------------------------------------------------------------------------

/// Live GitHub runner-group observation seam. No network implementation
/// exists yet; tests inject fakes.
#[allow(dead_code)]
pub trait FleetStateSource {
    fn observed_group(&self, organization: &str) -> Result<Option<ObservedGroup>>;
}

/// Normalized live group state read back from GitHub.
#[derive(Debug, Clone, PartialEq, Eq)]
#[allow(dead_code)]
pub struct ObservedGroup {
    pub name: String,
    pub visibility: String,
    pub allows_public_repositories: bool,
    pub restricted_to_workflows: bool,
    pub selected_repositories: BTreeSet<String>,
    /// Raw `owner/repo/.github/workflows/file.yml@ref` strings as reported.
    pub selected_workflows: BTreeSet<String>,
}

/// Normalize raw readback workflow strings into typed identities, rejecting
/// anything the policy contract forbids.
#[allow(dead_code)]
pub fn normalize_observed_workflows(raw: &BTreeSet<String>) -> Result<BTreeSet<WorkflowIdentity>> {
    let mut out = BTreeSet::new();
    for value in raw {
        let (path, git_ref) = value.rsplit_once('@').ok_or_else(|| {
            anyhow::anyhow!("field 'observed_workflows': value '{value}' lacks '@ref' suffix")
        })?;
        ensure_no_wildcard("observed_workflows", value)?;
        ensure_qualified_ref("observed_workflows", value, git_ref)?;
        split_identity_path("observed_workflows", value, path)?;
        out.insert(WorkflowIdentity {
            path: path.to_owned(),
            git_ref: git_ref.to_owned(),
        });
    }
    Ok(out)
}

/// Semantic equality between desired policy and observed readback; every
/// mismatch becomes one deterministic line.
#[allow(dead_code)]
pub fn semantic_diff(
    desired: &OrgPolicy,
    organization: &str,
    observed: &ObservedGroup,
) -> Result<Vec<String>> {
    validate_policy(desired)?;
    let mut diffs = Vec::new();
    if organization != desired.organization {
        diffs.push(format!(
            "organization: requested '{organization}' but policy targets '{}'",
            desired.organization
        ));
        return Ok(diffs);
    }
    if observed.name != desired.group_name {
        diffs.push(format!(
            "group_name: want '{}' got '{}'",
            desired.group_name, observed.name
        ));
    }
    if observed.visibility != desired.visibility.to_string() {
        diffs.push(format!(
            "visibility: want '{}' got '{}'",
            desired.visibility, observed.visibility
        ));
    }
    if observed.allows_public_repositories != desired.allows_public_repositories {
        diffs.push(format!(
            "allows_public_repositories: want '{}' got '{}'",
            desired.allows_public_repositories, observed.allows_public_repositories
        ));
    }
    if observed.restricted_to_workflows != desired.restricted_to_workflows {
        diffs.push(format!(
            "restricted_to_workflows: want '{}' got '{}'",
            desired.restricted_to_workflows, observed.restricted_to_workflows
        ));
    }
    let want_repos: BTreeSet<_> = desired.selected_repositories.iter().collect();
    let got_repos: BTreeSet<_> = observed.selected_repositories.iter().collect();
    for missing in want_repos.difference(&got_repos) {
        diffs.push(format!("selected_repositories: missing '{missing}'"));
    }
    for extra in got_repos.difference(&want_repos) {
        diffs.push(format!("selected_repositories: unexpected '{extra}'"));
    }
    let want_workflows = normalize_observed_workflows(&BTreeSet::from_iter(
        desired
            .selected_workflows
            .iter()
            .map(|identity| identity.to_selected_string()),
    ))?;
    let got_workflows = normalize_observed_workflows(&observed.selected_workflows)?;
    for missing in want_workflows.difference(&got_workflows) {
        diffs.push(format!("selected_workflows: missing '{missing}'"));
    }
    for extra in got_workflows.difference(&want_workflows) {
        diffs.push(format!("selected_workflows: unexpected '{extra}'"));
    }
    Ok(diffs)
}

// ---------------------------------------------------------------------------
// CLI boundary
// ---------------------------------------------------------------------------

#[derive(Debug, Args)]
pub struct FleetPolicyArgs {
    #[command(subcommand)]
    pub command: FleetPolicyCommand,
}

#[derive(Debug, Subcommand)]
pub enum FleetPolicyCommand {
    /// Print the deterministic desired-policy summary and digest (no mutation).
    Plan(FleetPlanArgs),
    /// Compare desired policy against live state (requires the live client).
    Audit(FleetAuditArgs),
    /// Apply a reviewed plan digest to exactly one organization (requires the live client).
    Apply(FleetApplyArgs),
    /// Regenerate per-org desired-policy JSON from the release-ref ledger offline.
    Generate(FleetGenerateArgs),
}

#[derive(Debug, Args)]
pub struct FleetPlanArgs {
    /// Generated policy JSON to plan from.
    #[arg(long)]
    pub policy: PathBuf,
    /// Optional release-ref ledger to cross-check.
    #[arg(long)]
    pub ledger: Option<PathBuf>,
}

#[derive(Debug, Args)]
pub struct FleetAuditArgs {
    /// Generated policy JSON to audit against.
    #[arg(long)]
    pub policy: PathBuf,
    /// Organization to audit (must match the policy's organization).
    #[arg(long)]
    pub organization: String,
}

#[derive(Debug, Args)]
pub struct FleetApplyArgs {
    /// Generated policy JSON to apply.
    #[arg(long)]
    pub policy: PathBuf,
    /// Exact organization to mutate; the whole operation is rejected otherwise.
    #[arg(long)]
    pub organization: String,
    /// Reviewed plan digest; a stale digest aborts before any mutation.
    #[arg(long)]
    pub plan_digest: String,
}

#[derive(Debug, Clone, Args)]
pub struct FleetGenerateArgs {
    /// Release-ref ledger to generate from (validated before any write).
    #[arg(long, default_value = "fleet/release-refs.toml")]
    pub ledger: PathBuf,
    /// Directory receiving `<org>-desired-policy.json` files.
    #[arg(long, default_value = "fleet/policies")]
    pub out_dir: PathBuf,
}

const NOT_IMPLEMENTED_LIVE: &str =
    "live GitHub API client not implemented in this build (Plan 039 Step 2 continues)";

/// Read the maintainer GitHub token from the environment. The value is never
/// echoed; errors name only the variable.
fn fleet_github_token() -> Result<String> {
    for variable in ["GITHUB_TOKEN", "GH_TOKEN"] {
        if let Ok(value) = std::env::var(variable) {
            if !value.trim().is_empty() {
                return Ok(value);
            }
        }
    }
    bail!("fleet operation requires a GitHub token in GITHUB_TOKEN (or GH_TOKEN); none found")
}

fn ensure_organization(policy: &OrgPolicy, organization: &str) -> Result<()> {
    if organization != policy.organization {
        bail!(
            "field 'organization': requested '{organization}' but policy targets '{}'; refusing to operate",
            policy.organization
        );
    }
    Ok(())
}

async fn live_gateway<'a>(
    http: &'a ReqwestFleetHttp,
) -> Result<FleetGateway<'a, ReqwestFleetHttp>> {
    let token = fleet_github_token()?;
    Ok(FleetGateway::new(http, &token, RetryPolicy::default()))
}

pub async fn fleet_policy(command: FleetPolicyCommand) -> Result<()> {
    match command {
        FleetPolicyCommand::Plan(args) => fleet_plan(args),
        FleetPolicyCommand::Audit(args) => fleet_audit(args).await,
        FleetPolicyCommand::Apply(args) => fleet_apply(args).await,
        FleetPolicyCommand::Generate(args) => fleet_generate(args),
    }
}

/// Build the deterministic per-organization desired policies from a validated
/// ledger.
///
/// Review-state mechanism (exact behavior that produced the committed
/// 2026-08-24 snapshots): [`validate_ledger`] rejects `expired` entries
/// outright, so every entry surviving validation — both `approved` and
/// `seed-pending-review` — flows into its organization's policy. The seed
/// ledger is entirely `seed-pending-review`, and the committed snapshots were
/// generated from it with all entries included; operator approval gates live
/// plan/audit/apply runs, not byte generation. Entries are grouped by owner;
/// repositories and workflow identities are sorted and de-duplicated by
/// [`OrgPolicy::normalized`] before canonical serialization.
pub fn generate_policies_from_ledger(ledger: &ReleaseRefLedger) -> Result<Vec<OrgPolicy>> {
    let mut by_org: BTreeMap<&str, Vec<&ReleaseRefEntry>> = BTreeMap::new();
    for entry in &ledger.entries {
        by_org.entry(entry.owner.as_str()).or_default().push(entry);
    }
    let mut policies = Vec::new();
    for (organization, entries) in &by_org {
        let mut policy = OrgPolicy::new((*organization).to_owned());
        let mut repositories = BTreeSet::new();
        let mut workflows = Vec::new();
        for entry in entries {
            repositories.insert(format!("{}/{}", entry.owner, entry.repository));
            workflows.push(WorkflowIdentity {
                path: format!(
                    "{}/{}/{}",
                    entry.owner, entry.repository, entry.workflow_path
                ),
                git_ref: entry.git_ref.clone(),
            });
        }
        policy.selected_repositories = repositories.into_iter().collect();
        policy.selected_workflows = workflows;
        let policy = policy.normalized();
        // Canonical JSON validates; a generated policy can never be invalid.
        policy.canonical_json()?;
        policies.push(policy);
    }
    if policies.is_empty() {
        bail!("field 'entries': value must be non-empty");
    }
    Ok(policies)
}

/// Mutation [`fleet_generate`] performs for one organization's policy file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum PolicyFileAction {
    /// On-disk bytes differ from (or no file carries) the generated bytes.
    Written,
    /// On-disk bytes already equal the generated bytes; leave mtime alone so
    /// drift stays observable through the filesystem.
    Skipped,
    /// `<org>-desired-policy.json` whose org is absent from the ledger.
    Removed,
}

/// One planned per-org change: the action plus the canonical bytes a write
/// would persist (`None` for removals).
type PlannedPolicyChange = (PolicyFileAction, Option<Vec<u8>>);

/// Pure decision core of [`fleet_generate`]: map every generated policy and
/// every existing `<org>-desired-policy.json` file (keyed by its org stem) to
/// a per-org action. `existing` must contain only entries whose filename
/// strictly matches `<org>-desired-policy.json`; callers never pass anything
/// else, so this function cannot decide to touch unrelated files.
fn plan_policy_actions(
    policies: &[OrgPolicy],
    existing: &BTreeMap<String, Vec<u8>>,
) -> Result<BTreeMap<String, PlannedPolicyChange>> {
    let mut plan = BTreeMap::new();
    let mut ledger_orgs = BTreeSet::new();
    for policy in policies {
        let bytes = format!("{}\n", policy.canonical_json()?);
        let action = if existing
            .get(&policy.organization)
            .is_some_and(|on_disk| on_disk.as_slice() == bytes.as_bytes())
        {
            PolicyFileAction::Skipped
        } else {
            PolicyFileAction::Written
        };
        ledger_orgs.insert(policy.organization.clone());
        plan.insert(
            policy.organization.clone(),
            (action, Some(bytes.into_bytes())),
        );
    }
    for org in existing.keys() {
        if !ledger_orgs.contains(org) {
            plan.insert(org.clone(), (PolicyFileAction::Removed, None));
        }
    }
    Ok(plan)
}

/// Scan `out_dir` for files named exactly `<org>-desired-policy.json` and
/// return stem → current bytes. Anything else in the directory (other names,
/// subdirectories) is ignored entirely and never becomes a removal candidate.
fn read_existing_policy_files(out_dir: &Path) -> Result<BTreeMap<String, Vec<u8>>> {
    let mut existing = BTreeMap::new();
    for entry in fs::read_dir(out_dir).with_context(|| format!("reading {}", out_dir.display()))? {
        let path = entry
            .with_context(|| format!("reading entry under {}", out_dir.display()))?
            .path();
        let name = path
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or_default();
        let Some(stem) = name.strip_suffix("-desired-policy.json") else {
            continue;
        };
        if stem.is_empty() || !path.is_file() {
            continue;
        }
        let bytes = fs::read(&path).with_context(|| format!("reading {}", path.display()))?;
        existing.insert(stem.to_owned(), bytes);
    }
    Ok(existing)
}

fn fleet_generate(args: FleetGenerateArgs) -> Result<()> {
    let ledger = ReleaseRefLedger::load(&args.ledger)?;
    let policies = generate_policies_from_ledger(&ledger)?;
    fs::create_dir_all(&args.out_dir)
        .with_context(|| format!("creating {}", args.out_dir.display()))?;
    let existing = read_existing_policy_files(&args.out_dir)?;
    let plan = plan_policy_actions(&policies, &existing)?;
    let by_org: BTreeMap<&str, &OrgPolicy> = policies
        .iter()
        .map(|policy| (policy.organization.as_str(), policy))
        .collect();
    for (org, (action, bytes)) in &plan {
        let path = args.out_dir.join(format!("{org}-desired-policy.json"));
        match action {
            PolicyFileAction::Written => {
                let bytes = bytes
                    .as_deref()
                    .expect("written actions always carry generated bytes");
                fs::write(&path, bytes)
                    .with_context(|| format!("writing fleet policy {}", path.display()))?;
                let policy = by_org[org.as_str()];
                println!(
                    "{}: {} repos, {} workflows, {}",
                    path.display(),
                    policy.selected_repositories.len(),
                    policy.selected_workflows.len(),
                    policy.digest()?
                );
            }
            PolicyFileAction::Skipped => {
                println!("{}: already current; left untouched", path.display());
            }
            PolicyFileAction::Removed => {
                fs::remove_file(&path)
                    .with_context(|| format!("removing stale fleet policy {}", path.display()))?;
                println!(
                    "{}: removed; organization absent from {}",
                    path.display(),
                    args.ledger.display()
                );
            }
        }
    }
    Ok(())
}

async fn fleet_audit(args: FleetAuditArgs) -> Result<()> {
    let policy = load_policy(&args.policy)?;
    ensure_organization(&policy, &args.organization)?;
    let http = ReqwestFleetHttp::new(DEFAULT_GITHUB_API_URL, &fleet_github_token()?)?;
    let gateway = live_gateway(&http).await?;
    let mismatches = gateway.audit(&policy, &args.organization).await?;
    if mismatches.is_empty() {
        println!(
            "fleet audit: '{}' matches the reviewed plan digest exactly",
            args.organization
        );
        return Ok(());
    }
    println!("fleet audit: {} mismatch class(es):", mismatches.len());
    for line in &mismatches {
        println!("  {line}");
    }
    bail!("fleet audit: drift detected; no mutation was performed")
}

async fn fleet_apply(args: FleetApplyArgs) -> Result<()> {
    let policy = load_policy(&args.policy)?;
    ensure_organization(&policy, &args.organization)?;
    // Digest gate before any HTTP call happens inside apply_reviewed_policy;
    // verify here too so a stale digest never even builds a transport.
    verify_plan_digest(&args.plan_digest, policy.digest()?.as_str())?;
    let http = ReqwestFleetHttp::new(DEFAULT_GITHUB_API_URL, &fleet_github_token()?)?;
    let gateway = live_gateway(&http).await?;
    let stages = gateway
        .apply_reviewed_policy(&policy, &args.organization, &args.plan_digest)
        .await?;
    println!("fleet apply: '{}':", args.organization);
    for stage in &stages {
        println!("  {stage}");
    }
    Ok(())
}

fn load_policy(path: &Path) -> Result<OrgPolicy> {
    let raw = fs::read_to_string(path)
        .with_context(|| format!("reading fleet policy {}", path.display()))?;
    let policy: OrgPolicy = serde_json::from_str(&raw)
        .with_context(|| format!("parsing fleet policy {}", path.display()))?;
    validate_policy(&policy)?;
    Ok(policy)
}

fn fleet_plan(args: FleetPlanArgs) -> Result<()> {
    let policy = load_policy(&args.policy)?;
    if let Some(ledger_path) = &args.ledger {
        ReleaseRefLedger::load(ledger_path)?;
    }
    println!("organization: {}", policy.organization);
    println!("group: {}", policy.group_name);
    println!(
        "repositories ({}): {}",
        policy.selected_repositories.len(),
        policy.selected_repositories.join(", ")
    );
    println!("workflows ({}):", policy.selected_workflows.len());
    for identity in &policy.selected_workflows {
        println!("  {identity}");
    }
    println!("digest: {}", policy.digest()?);
    println!("note: observed-state section unavailable; {NOT_IMPLEMENTED_LIVE}");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_policy() -> OrgPolicy {
        let mut policy = OrgPolicy::new("tailrocks");
        policy.selected_repositories = vec![
            "tailrocks/schemalane".to_owned(),
            "tailrocks/ruxel".to_owned(),
        ];
        policy.selected_workflows = vec![
            WorkflowIdentity {
                path: "tailrocks/ruxel/.github/workflows/ci.yml".to_owned(),
                git_ref: "refs/heads/main".to_owned(),
            },
            WorkflowIdentity {
                path: "tailrocks/schemalane/.github/workflows/ci.yml".to_owned(),
                git_ref: "refs/heads/trunk".to_owned(),
            },
        ];
        policy.normalized()
    }

    fn sample_ledger() -> ReleaseRefLedger {
        ReleaseRefLedger {
            schema_version: 1,
            entries: vec![ReleaseRefEntry {
                owner: "tailrocks".to_owned(),
                repository: "velnor-actions-fixture".to_owned(),
                workflow_path: ".github/workflows/ci.yml".to_owned(),
                git_ref: "refs/heads/main".to_owned(),
                admission_reason: "fixture default-branch CI defines direct jobs".to_owned(),
                approving_change: "SEED-PENDING-OPERATOR-REVIEW (plan-039)".to_owned(),
                review_state: ReviewState::SeedPendingReview,
                expiry: None,
            }],
        }
    }

    #[test]
    fn golden_canonical_serialization() {
        let policy = sample_policy();
        let json = policy.canonical_json().expect("canonical json");
        assert_eq!(
            json,
            "{\"schema_version\":1,\"contract_version\":\"1\",\"generator_version\":\"fleet-policy-gen/1\",\"organization\":\"tailrocks\",\"group_name\":\"velnor-trusted\",\"runner_labels\":[\"velnor-target-mvp\"],\"visibility\":\"selected\",\"allows_public_repositories\":true,\"restricted_to_workflows\":true,\"selected_repositories\":[\"tailrocks/ruxel\",\"tailrocks/schemalane\"],\"selected_workflows\":[{\"path\":\"tailrocks/ruxel/.github/workflows/ci.yml\",\"ref\":\"refs/heads/main\"},{\"path\":\"tailrocks/schemalane/.github/workflows/ci.yml\",\"ref\":\"refs/heads/trunk\"}]}"
        );
    }

    #[test]
    fn sort_and_dedup_enforced() {
        let mut policy = sample_policy();
        policy.selected_repositories = vec![
            "tailrocks/zeta".to_owned(),
            "tailrocks/alpha".to_owned(),
            "tailrocks/zeta".to_owned(),
        ];
        policy.selected_workflows.push(WorkflowIdentity {
            path: "tailrocks/ruxel/.github/workflows/ci.yml".to_owned(),
            git_ref: "refs/heads/main".to_owned(),
        });
        let normalized = policy.normalized();
        assert_eq!(
            normalized.selected_repositories,
            vec!["tailrocks/alpha".to_owned(), "tailrocks/zeta".to_owned()]
        );
        assert_eq!(normalized.selected_workflows.len(), 2);

        // Hand-built (un-normalized) structs must still be rejected.
        let mut unsorted = sample_policy();
        unsorted.selected_repositories = vec![
            "tailrocks/schemalane".to_owned(),
            "tailrocks/ruxel".to_owned(),
            "tailrocks/ruxel".to_owned(),
        ];
        let err = validate_policy(&unsorted).unwrap_err().to_string();
        assert!(err.contains("field 'selected_repositories'"), "{err}");
        assert!(err.contains("duplicate-free"), "{err}");
    }

    #[test]
    fn reject_empty_workflows_and_repositories() {
        let mut policy = sample_policy();
        policy.selected_workflows.clear();
        assert_eq!(
            validate_policy(&policy).unwrap_err().to_string(),
            "field 'selected_workflows': value must be non-empty"
        );
        let mut policy = sample_policy();
        policy.selected_repositories.clear();
        assert_eq!(
            validate_policy(&policy).unwrap_err().to_string(),
            "field 'selected_repositories': value must be non-empty"
        );
    }

    #[test]
    fn reject_missing_repository_entry() {
        let mut policy = sample_policy();
        policy.selected_repositories.remove(0);
        let err = validate_policy(&policy).unwrap_err().to_string();
        assert!(
            err.contains("references repository 'tailrocks/ruxel' absent"),
            "{err}"
        );
    }

    #[test]
    fn reject_extra_repository_entry() {
        let mut policy = sample_policy();
        policy
            .selected_repositories
            .push("tailrocks/termrock".to_owned());
        let err = validate_policy(&policy).unwrap_err().to_string();
        assert!(
            err.contains("'tailrocks/termrock' has no 'selected_workflows' entry"),
            "{err}"
        );
    }

    #[test]
    fn reject_duplicate_workflow_entry() {
        let mut policy = sample_policy();
        let dup = policy.selected_workflows[0].clone();
        policy.selected_workflows.push(dup);
        let err = validate_policy(&policy).unwrap_err().to_string();
        assert!(err.contains("duplicate entry"), "{err}");
    }

    #[test]
    fn reject_wildcard_entry() {
        let mut policy = sample_policy();
        policy.selected_workflows[0].git_ref = "refs/heads/*".to_owned();
        let err = validate_policy(&policy).unwrap_err().to_string();
        assert!(
            err.contains("must not contain wildcards") && err.contains("refs/heads/*"),
            "{err}"
        );

        let mut policy = sample_policy();
        policy.selected_workflows[0].path = "tailrocks/ruxel/.github/workflows/*.yml".to_owned();
        let err = validate_policy(&policy).unwrap_err().to_string();
        assert!(err.contains("wildcards"), "{err}");
    }

    #[test]
    fn reject_unqualified_refs() {
        for bad in ["main", "v1.2.3", "", "refs/heads/", "HEAD"] {
            let mut policy = sample_policy();
            policy.selected_workflows[0].git_ref = bad.to_owned();
            let err = validate_policy(&policy).unwrap_err().to_string();
            assert!(
                err.contains("unqualified ref"),
                "ref '{bad}' not rejected: {err}"
            );
        }
    }

    #[test]
    fn accept_qualified_refs() {
        let mut policy = sample_policy();
        policy.selected_workflows[0].git_ref =
            "0123456789012345678901234567890123456789".to_owned();
        assert!(validate_policy(&policy).is_ok());
        policy.selected_workflows[0].git_ref = "refs/tags/v0.1.98".to_owned();
        assert!(validate_policy(&policy).is_ok());
    }

    #[test]
    fn reject_contradictory_entries_same_path_different_refs() {
        let mut policy = sample_policy();
        policy.selected_workflows.push(WorkflowIdentity {
            path: "tailrocks/ruxel/.github/workflows/ci.yml".to_owned(),
            git_ref: "refs/heads/release".to_owned(),
        });
        let err = validate_policy(&policy).unwrap_err().to_string();
        assert!(
            err.contains("contradictory entries for workflow path"),
            "{err}"
        );
    }

    #[test]
    fn digest_stable_across_key_permutation() {
        let a = sample_policy();
        let mut b = sample_policy();
        b.selected_repositories.reverse();
        b.selected_workflows.reverse();
        let unsorted_repos = b.selected_repositories.clone();
        let b = b.normalized();
        // The permutation was real, yet normalization plus canonical JSON
        // make both digests identical.
        assert_ne!(unsorted_repos, b.selected_repositories);
        assert_eq!(a.digest().expect("digest a"), b.digest().expect("digest b"));
    }

    #[test]
    fn version_bump_changes_digest() {
        let mut bumped = sample_policy();
        bumped.contract_version = "2".to_owned();
        // Digest input bytes differ when only the version field differs.
        let base_bytes = serde_json::to_vec(&sample_policy()).expect("serialize base");
        let bumped_bytes = serde_json::to_vec(&bumped).expect("serialize bumped");
        assert_ne!(
            format!("sha256:{}", hex_digest(&base_bytes)),
            format!("sha256:{}", hex_digest(&bumped_bytes))
        );
        // A policy carrying an unsupported version fails validation by name.
        let err = bumped.digest().unwrap_err().to_string();
        assert!(err.contains("field 'contract_version'"), "{err}");
    }

    #[test]
    fn digest_changes_when_entries_change() {
        let base = sample_policy();
        let mut changed = base.clone();
        changed.selected_workflows[0].git_ref = "refs/tags/v9".to_owned();
        assert_ne!(
            base.digest().expect("base"),
            changed.digest().expect("changed")
        );
    }

    #[test]
    fn stale_digest_detection_names_both_values() {
        let err = verify_plan_digest("sha256:deadbeef", "sha256:cafebabe")
            .unwrap_err()
            .to_string();
        assert!(err.contains("stale"), "{err}");
        assert!(err.contains("sha256:deadbeef"), "{err}");
        assert!(err.contains("sha256:cafebabe"), "{err}");
        assert!(verify_plan_digest("sha256:same", "sha256:same").is_ok());
    }

    #[test]
    fn ledger_seed_file_parses_and_is_pending_review() {
        let manifest = env!("CARGO_MANIFEST_DIR");
        let path = Path::new(manifest)
            .join("../..")
            .join("fleet/release-refs.toml");
        let ledger = ReleaseRefLedger::load(&path).expect("seed ledger parses");
        assert_eq!(ledger.schema_version, 1);
        assert!(ledger
            .entries
            .iter()
            .all(|entry| matches!(entry.review_state, ReviewState::SeedPendingReview)));
        assert!(ledger
            .approved_workflow_identities()
            .expect("identities")
            .is_empty());
    }

    #[test]
    fn ledger_approved_identities_flow_into_policy_shape() {
        let mut ledger = sample_ledger();
        ledger.entries[0].review_state = ReviewState::Approved;
        let identities = ledger.approved_workflow_identities().expect("identities");
        assert_eq!(
            identities,
            vec![WorkflowIdentity {
                path: "tailrocks/velnor-actions-fixture/.github/workflows/ci.yml".to_owned(),
                git_ref: "refs/heads/main".to_owned(),
            }]
        );
    }

    #[test]
    fn ledger_rejects_bad_fields_and_contradictions() {
        let mut ledger = sample_ledger();
        ledger.entries[0].git_ref = "main".to_owned();
        let err = validate_ledger(&ledger).unwrap_err().to_string();
        assert!(err.contains("unqualified ref"), "{err}");

        let mut ledger = sample_ledger();
        ledger.entries[0].workflow_path = ".github/workflows/*.yml".to_owned();
        let err = validate_ledger(&ledger).unwrap_err().to_string();
        assert!(err.contains("wildcards"), "{err}");

        let mut ledger = sample_ledger();
        ledger.entries.push(ReleaseRefEntry {
            git_ref: "refs/heads/release".to_owned(),
            ..sample_ledger().entries[0].clone()
        });
        let err = validate_ledger(&ledger).unwrap_err().to_string();
        assert!(err.contains("contradictory entries"), "{err}");

        let mut ledger = sample_ledger();
        ledger.entries[0].review_state = ReviewState::Expired;
        let err = validate_ledger(&ledger).unwrap_err().to_string();
        assert!(err.contains("expired"), "{err}");

        let mut ledger = sample_ledger();
        ledger.entries[0].expiry = Some("2026-13-99".to_owned());
        let err = validate_ledger(&ledger).unwrap_err().to_string();
        assert!(err.contains("YYYY-MM-DD"), "{err}");

        let mut ledger = sample_ledger();
        ledger.schema_version = 99;
        let err = validate_ledger(&ledger).unwrap_err().to_string();
        assert!(err.contains("schema_version"), "{err}");
    }

    #[test]
    fn observed_readback_normalization_rejects_garbage() {
        let err = normalize_observed_workflows(&BTreeSet::from([
            "tailrocks/ruxel/.github/workflows/ci.yml@main".to_owned(),
        ]))
        .unwrap_err()
        .to_string();
        assert!(err.contains("unqualified ref"), "{err}");

        let err = normalize_observed_workflows(&BTreeSet::from(["no-ref-here".to_owned()]))
            .unwrap_err()
            .to_string();
        assert!(err.contains("@ref"), "{err}");

        let ok = normalize_observed_workflows(&BTreeSet::from([
            "tailrocks/ruxel/.github/workflows/ci.yml@refs/heads/main".to_owned(),
        ]))
        .expect("normalizes");
        assert_eq!(ok.len(), 1);
    }

    #[test]
    fn semantic_diff_reports_every_mismatch_class() {
        let desired = sample_policy();
        let observed = ObservedGroup {
            name: "Default".to_owned(),
            visibility: "private".to_owned(),
            allows_public_repositories: false,
            restricted_to_workflows: false,
            selected_repositories: BTreeSet::from(["tailrocks/ruxel".to_owned()]),
            selected_workflows: BTreeSet::from([
                "tailrocks/ruxel/.github/workflows/release.yml@refs/heads/main".to_owned(),
            ]),
        };
        let diffs = semantic_diff(&desired, "tailrocks", &observed).expect("diff");
        assert!(
            diffs.iter().any(|line| line.contains("group_name")),
            "{diffs:?}"
        );
        assert!(
            diffs.iter().any(|line| line.contains("visibility")),
            "{diffs:?}"
        );
        assert!(
            diffs
                .iter()
                .any(|line| line.contains("allows_public_repositories")),
            "{diffs:?}"
        );
        assert!(
            diffs
                .iter()
                .any(|line| line.contains("restricted_to_workflows")),
            "{diffs:?}"
        );
        assert!(
            diffs
                .iter()
                .any(|line| line.contains("missing 'tailrocks/schemalane'")),
            "{diffs:?}"
        );
        assert!(
            !diffs
                .iter()
                .any(|line| line.contains("unexpected 'tailrocks/ruxel'")),
            "ruxel is desired: {diffs:?}"
        );
        assert!(
            diffs
                .iter()
                .any(|line| line.contains("selected_workflows: missing")),
            "{diffs:?}"
        );
        assert!(
            diffs
                .iter()
                .any(|line| line.contains("selected_workflows: unexpected")),
            "{diffs:?}"
        );

        // Exact readback produces zero drift.
        let exact = ObservedGroup {
            name: desired.group_name.clone(),
            visibility: "selected".to_owned(),
            allows_public_repositories: true,
            restricted_to_workflows: true,
            selected_repositories: desired.selected_repositories.iter().cloned().collect(),
            selected_workflows: BTreeSet::from([
                "tailrocks/ruxel/.github/workflows/ci.yml@refs/heads/main".to_owned(),
                "tailrocks/schemalane/.github/workflows/ci.yml@refs/heads/trunk".to_owned(),
            ]),
        };
        assert!(semantic_diff(&desired, "tailrocks", &exact)
            .expect("diff")
            .is_empty());
        // Wrong organization short-circuits deterministically.
        let errs = semantic_diff(&desired, "ChainArgos", &exact).expect("diff");
        assert_eq!(errs.len(), 1);
        assert!(errs[0].contains("requested 'ChainArgos'"), "{}", errs[0]);
    }

    #[test]
    fn fake_state_source_seam_compiles_without_network() {
        struct FakeSource(ObservedGroup);
        impl FleetStateSource for FakeSource {
            fn observed_group(&self, _organization: &str) -> Result<Option<ObservedGroup>> {
                Ok(Some(self.0.clone()))
            }
        }
        let desired = sample_policy();
        let source = FakeSource(ObservedGroup {
            name: desired.group_name.clone(),
            visibility: "selected".to_owned(),
            allows_public_repositories: true,
            restricted_to_workflows: true,
            selected_repositories: desired.selected_repositories.iter().cloned().collect(),
            selected_workflows: BTreeSet::from([
                "tailrocks/ruxel/.github/workflows/ci.yml@refs/heads/main".to_owned(),
                "tailrocks/schemalane/.github/workflows/ci.yml@refs/heads/trunk".to_owned(),
            ]),
        });
        let observed = source
            .observed_group("tailrocks")
            .expect("fake fetch")
            .expect("present");
        assert!(semantic_diff(&desired, "tailrocks", &observed)
            .expect("diff")
            .is_empty());
    }

    fn repo_root() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
    }

    #[test]
    fn generate_reproduces_committed_snapshot_bytes() {
        let ledger =
            ReleaseRefLedger::load(&repo_root().join("fleet/release-refs.toml")).expect("ledger");
        let policies = generate_policies_from_ledger(&ledger).expect("policies");
        let mut seen = BTreeSet::new();
        for policy in &policies {
            seen.insert(policy.organization.clone());
            let generated = format!("{}\n", policy.canonical_json().expect("canonical"));
            let snapshot = repo_root()
                .join(".velnor-compare/2026-08-24-039-snapshots")
                .join(format!("{}-desired-policy.json", policy.organization));
            let committed = fs::read_to_string(&snapshot)
                .unwrap_or_else(|error| panic!("read {snapshot:?}: {error}"));
            assert_eq!(
                generated,
                committed,
                "generated bytes diverge from {}",
                snapshot.display()
            );
        }
        assert_eq!(
            seen,
            BTreeSet::from([
                "ChainArgos".to_owned(),
                "jackin-project".to_owned(),
                "tailrocks".to_owned(),
            ])
        );
    }

    #[test]
    fn generate_is_deterministic_across_runs() {
        let ledger =
            ReleaseRefLedger::load(&repo_root().join("fleet/release-refs.toml")).expect("ledger");
        let first = generate_policies_from_ledger(&ledger).expect("first");
        let second = generate_policies_from_ledger(&ledger).expect("second");
        assert_eq!(first.len(), second.len());
        for (left, right) in first.iter().zip(second.iter()) {
            assert_eq!(left, right);
            assert_eq!(
                left.canonical_json().expect("left"),
                right.canonical_json().expect("right")
            );
            assert_eq!(left.digest().expect("left"), right.digest().expect("right"));
        }
    }

    fn ledger_toml(entries: &[String]) -> String {
        let mut text = String::from("schema_version = 1\n");
        for entry in entries {
            text.push_str(entry);
        }
        text
    }

    fn base_entry() -> String {
        "[[entries]]\n\
         owner = \"tailrocks\"\n\
         repository = \"ruxel\"\n\
         workflow_path = \".github/workflows/ci.yml\"\n\
         git_ref = \"refs/heads/main\"\n\
         admission_reason = \"test\"\n\
         approving_change = \"test\"\n\
         review_state = \"seed-pending-review\"\n"
            .to_owned()
    }

    fn parsed_ledger_error(text: &str) -> String {
        let parsed: ReleaseRefLedger =
            toml::from_str(text).expect("malformed fixtures must stay TOML-parseable");
        validate_ledger(&parsed)
            .err()
            .map(|error| error.to_string())
            .expect("ledger must be rejected")
    }

    #[test]
    fn generation_fails_loudly_on_duplicate_entries() {
        let mut duplicate = base_entry();
        duplicate.push_str(&base_entry());
        let err = parsed_ledger_error(&ledger_toml(&[duplicate]));
        assert!(err.contains("field 'entries': duplicate entry"), "{err}");
    }

    #[test]
    fn generation_fails_loudly_on_wildcards() {
        let mut wildcard = base_entry();
        wildcard = wildcard.replace(
            "workflow_path = \".github/workflows/ci.yml\"",
            "workflow_path = \".github/workflows/*.yml\"",
        );
        let err = parsed_ledger_error(&ledger_toml(&[wildcard]));
        assert!(err.contains("wildcards"), "{err}");
    }

    #[test]
    fn generation_fails_loudly_on_unqualified_refs() {
        let unqualified =
            base_entry().replace("git_ref = \"refs/heads/main\"", "git_ref = \"main\"");
        let err = parsed_ledger_error(&ledger_toml(&[unqualified]));
        assert!(err.contains("unqualified ref"), "{err}");
    }

    #[test]
    fn generation_fails_loudly_on_contradictions() {
        let mut conflicting = base_entry();
        conflicting = conflicting.replace(
            "git_ref = \"refs/heads/main\"",
            "git_ref = \"refs/tags/v9\"",
        );
        let err = parsed_ledger_error(&ledger_toml(&[base_entry(), conflicting]));
        assert!(err.contains("contradictory entries"), "{err}");

        // Policy-layer backstop: even an unvalidated in-memory ledger cannot
        // reach canonical bytes with two refs for one workflow path.
        let mut ledger = sample_ledger();
        ledger.entries.push(ReleaseRefEntry {
            git_ref: "refs/heads/release".to_owned(),
            ..sample_ledger().entries[0].clone()
        });
        let err = generate_policies_from_ledger(&ledger)
            .map(|policies| policies[0].canonical_json().expect("canonical"))
            .unwrap_err()
            .to_string();
        assert!(
            err.contains("contradictory entries for workflow path"),
            "{err}"
        );
    }

    struct PolicyDir {
        path: PathBuf,
    }

    impl PolicyDir {
        fn new(tag: &str) -> Self {
            let nonce = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos();
            let path = std::env::temp_dir().join(format!("velnor-policy-gen-{tag}-{nonce}"));
            fs::create_dir_all(&path).expect("create policy dir");
            Self { path }
        }
    }

    impl Drop for PolicyDir {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.path);
        }
    }

    #[test]
    fn plan_policy_actions_classifies_write_skip_and_remove() {
        let mut ledger = sample_ledger();
        let mut second = ledger.entries[0].clone();
        second.owner = "ChainArgos".to_owned();
        second.repository = "velnor".to_owned();
        ledger.entries.push(second);
        let policies = generate_policies_from_ledger(&ledger).expect("policies");
        assert_eq!(policies.len(), 2);
        let tailrocks = policies
            .iter()
            .find(|policy| policy.organization == "tailrocks")
            .expect("tailrocks policy");
        let current = format!("{}\n", tailrocks.canonical_json().expect("canonical"));
        let mut existing = BTreeMap::new();
        // Byte-identical file is skipped.
        existing.insert("tailrocks".to_owned(), current.clone().into_bytes());
        // Drifted bytes for a live org are rewritten.
        existing.insert("ChainArgos".to_owned(), b"{}\n".to_vec());
        // Org absent from the ledger is removed.
        existing.insert("ghost-org".to_owned(), b"stale\n".to_vec());

        let plan = plan_policy_actions(&policies, &existing).expect("plan");
        assert_eq!(plan.len(), 3, "{plan:?}");
        assert_eq!(
            plan.get("tailrocks").expect("tailrocks").0,
            PolicyFileAction::Skipped
        );
        assert_eq!(
            plan.get("ChainArgos").expect("ChainArgos").0,
            PolicyFileAction::Written
        );
        assert_eq!(
            plan.get("ghost-org").expect("ghost-org").0,
            PolicyFileAction::Removed
        );

        // Missing on-disk state means every ledger org is written.
        let fresh = plan_policy_actions(&policies, &BTreeMap::new()).expect("fresh plan");
        assert_eq!(fresh.len(), 2);
        assert_eq!(fresh["tailrocks"].0, PolicyFileAction::Written);
        assert_eq!(
            fresh["tailrocks"].1.as_deref().expect("bytes"),
            current.as_bytes()
        );
    }

    #[test]
    fn generate_second_run_leaves_current_files_untouched() {
        let dir = PolicyDir::new("idempotent");
        let args = FleetGenerateArgs {
            ledger: repo_root().join("fleet/release-refs.toml"),
            out_dir: dir.path.clone(),
        };
        fleet_generate(args.clone()).expect("first generate");
        let path = dir.path.join("tailrocks-desired-policy.json");
        let content = fs::read_to_string(&path).expect("generated content");
        let pinned = std::time::UNIX_EPOCH + std::time::Duration::from_secs(1);
        fs::OpenOptions::new()
            .append(true)
            .open(&path)
            .expect("open")
            .set_modified(pinned)
            .expect("pin mtime");

        fleet_generate(args).expect("second generate");

        let metadata = fs::metadata(&path).expect("metadata");
        assert_eq!(content, fs::read_to_string(&path).expect("same content"));
        assert_eq!(
            metadata.modified().expect("mtime"),
            pinned,
            "file rewritten"
        );
    }

    #[test]
    fn generate_removes_stale_org_file() {
        let dir = PolicyDir::new("stale");
        let stale = dir.path.join("ghost-org-desired-policy.json");
        fs::write(&stale, b"stale bytes\n").expect("seed stale org");

        let args = FleetGenerateArgs {
            ledger: repo_root().join("fleet/release-refs.toml"),
            out_dir: dir.path.clone(),
        };
        fleet_generate(args).expect("generate");

        assert!(!stale.exists(), "stale org file must be removed");
        assert!(
            dir.path.join("tailrocks-desired-policy.json").is_file(),
            "live org still generated"
        );
    }

    #[test]
    fn generate_never_touches_unrelated_directory_entries() {
        let dir = PolicyDir::new("unrelated");
        let unrelated: Vec<(PathBuf, &[u8])> = vec![
            (dir.path.join("README.md"), b"docs\n"),
            (dir.path.join(".gitkeep"), b""),
            (dir.path.join("notes.txt"), b"keep me\n"),
            (
                dir.path.join("tailrocks-desired-policy.json.bak"),
                b"backup\n",
            ),
            (dir.path.join("desired-policy.json"), b"no org prefix\n"),
            (
                dir.path
                    .join("subdir-desired-policy.json/tailrocks-desired-policy.json"),
                b"inside directory\n",
            ),
        ];
        for (path, bytes) in &unrelated {
            fs::create_dir_all(path.parent().expect("parent")).expect("mkdirs");
            fs::write(path, bytes).expect("seed unrelated entry");
        }

        let args = FleetGenerateArgs {
            ledger: repo_root().join("fleet/release-refs.toml"),
            out_dir: dir.path.clone(),
        };
        fleet_generate(args).expect("generate");

        for (path, bytes) in &unrelated {
            assert_eq!(
                fs::read(path).ok(),
                Some(bytes.to_vec()),
                "{} must be untouched",
                path.display()
            );
        }
        // A bare `-desired-policy.json` (empty org stem) is not an org file.
        assert!(fs::read(dir.path.join("-desired-policy.json")).is_err());
        // The lookalike directory itself survives with its contents.
        assert!(dir.path.join("subdir-desired-policy.json").is_dir());
    }
}
