//! The generated-surface contract of tailrocks/velnor.
//!
//! The generator is generic; this repository teaches it everything specific to
//! itself through `.github-gen/velnor-workflow.toml`. These tests hold the
//! lines that used to live inside the crate: the generator owns every
//! generated file under `.github`, the bootstrap action is owned verbatim,
//! and the Rust unit workflow realizes exactly its declared backends.

use std::fs;
use std::path::{Path, PathBuf};

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .canonicalize()
        .expect("repository root resolves")
}

fn read(path: &str) -> String {
    fs::read_to_string(repository_root().join(path))
        .unwrap_or_else(|error| panic!("read {path}: {error}"))
}

/// Return the indented YAML block below a top-level mapping key.
///
/// The contract crate intentionally has no YAML parser dependency. These
/// workflows are generated from a fixed schema, so checking the indentation
/// boundaries keeps the assertions about event and permission ownership
/// structural without treating a substring elsewhere in the file as proof.
fn top_level_block<'a>(workflow: &'a str, key: &str) -> Vec<&'a str> {
    let header = format!("{key}:");
    let mut lines = workflow.lines();
    lines
        .by_ref()
        .find(|line| *line == header)
        .unwrap_or_else(|| panic!("top-level `{key}:` is missing"));
    lines
        .take_while(|line| line.is_empty() || line.starts_with(' ') || line.starts_with('\t'))
        .collect()
}

fn top_level_block_text(workflow: &str, key: &str) -> String {
    top_level_block(workflow, key)
        .join("\n")
        .trim_end()
        .to_owned()
}

fn generated_files() -> Vec<(String, String)> {
    let workflows = repository_root().join(".github/workflows");
    let mut files: Vec<(String, String)> = fs::read_dir(&workflows)
        .expect("read .github/workflows")
        .map(|entry| entry.expect("workflow entry").path())
        .filter(|path| path.extension().is_some_and(|extension| extension == "yml"))
        .map(|path| {
            let name = path.file_name().unwrap().to_str().unwrap().to_owned();
            let content = fs::read_to_string(&path).expect("read workflow");
            (name, content)
        })
        .collect();
    files.sort_by(|a, b| a.0.cmp(&b.0));
    files
}

/// The generated project config and declared static-file mappings own every
/// checked-in workflow. Static workflow sources are copied verbatim by the
/// active renderer and therefore are ownership declarations too.
#[test]
fn the_generator_owns_every_current_workflow() {
    let project = read(".github/ci/project.toml");
    assert!(project.starts_with("# Generated by velnor-workflow."));
    let mut declared = project
        .lines()
        .find_map(|line| line.strip_prefix("files = ["))
        .map(|rest| rest.trim_end_matches(']').to_owned())
        .expect("project config declares its workflow files");
    let source_config = read(".github-gen/velnor-workflow.toml");
    for line in source_config.lines() {
        if let Some(path) = line.strip_prefix("file = \"") {
            let name = Path::new(path.trim_end_matches('"'))
                .file_name()
                .and_then(|name| name.to_str())
                .expect("static file has a UTF-8 basename");
            declared.push_str(&format!("\"{name}\""));
        }
    }

    let checked_in: Vec<String> = generated_files()
        .into_iter()
        .map(|(name, _)| name)
        .collect();
    for name in &checked_in {
        assert!(
            declared.contains(&format!("\"{name}\"")),
            "{name} exists under .github/workflows but the generated project config does not own it"
        );
    }
    for (name, content) in generated_files() {
        assert!(
            content.starts_with("# Generated by velnor-workflow."),
            "{name} is missing the generator header"
        );
    }
}

/// Candidate qualification is an unprivileged static workflow. It runs the
/// PR-built renderer only against disposable outputs and cannot supply active
/// policy or publication authority.
#[test]
fn candidate_qualification_is_unprivileged_and_deterministic() {
    let source = read(".github-gen/sources/workflows/candidate-qualification.yml");
    let generated = read(".github/workflows/candidate-qualification.yml");
    assert_eq!(
        source, generated,
        "the candidate workflow source was not copied byte-for-byte into the generated surface"
    );

    let events = top_level_block_text(&source, "on");
    assert!(events.contains("  pull_request:"), "{events}");
    assert_eq!(
        events
            .lines()
            .filter(|line| line.starts_with("  ") && !line.starts_with("    "))
            .count(),
        1,
        "candidate qualification must have exactly one trigger event: {events}"
    );
    for path in [
        "crates/velnor-workflow/**",
        ".github-gen/**",
        ".github-gen/sources/workflows/candidate-qualification.yml",
        "Cargo.lock",
        "Cargo.toml",
        "rust-toolchain",
        "rust-toolchain.toml",
        ".cargo/**",
    ] {
        assert!(
            events.contains(&format!("      - '{path}'")),
            "candidate qualification does not trigger for `{path}`: {events}"
        );
    }
    let concurrency = top_level_block_text(&source, "concurrency");
    assert!(
        concurrency.contains(
            "group: candidate-qualification-${{ github.repository }}-${{ github.event.pull_request.number || github.ref }}"
        ),
        "candidate qualification must isolate cancellation by pull request: {concurrency}"
    );
    assert!(
        concurrency.contains("cancel-in-progress: true"),
        "candidate qualification must cancel superseded commits: {concurrency}"
    );
    assert!(!source.contains("pull_request_target"), "{source}");
    assert!(!source.contains("workflow_run:"), "{source}");

    let permissions = top_level_block_text(&source, "permissions");
    assert_eq!(permissions, "  contents: read");
    assert_eq!(source.matches("\npermissions:").count(), 1);
    assert!(!source.contains("contents: write"), "{source}");
    assert!(!source.contains("id-token: write"), "{source}");
    assert!(!source.contains("actions: write"), "{source}");

    assert!(source.contains("persist-credentials: false"), "{source}");
    assert!(
        source.contains("env -u GITHUB_TOKEN -u GH_TOKEN -u ACTIONS_ID_TOKEN_REQUEST_TOKEN"),
        "{source}"
    );
    assert!(
        source.contains("candidate_root=\"$(mktemp -d)\""),
        "{source}"
    );
    assert_eq!(
        source
            .matches("--force --output \"$candidate_root/")
            .count(),
        2
    );
    assert!(
        source.contains("diff -ru \"$candidate_root/one\" \"$candidate_root/two\""),
        "{source}"
    );
    assert!(
        !source.contains("--output ."),
        "candidate output must stay disposable: {source}"
    );
}

/// The bootstrap composite action is repository-owned bytes under
/// `.github-gen/sources`; the generator copies it into `.github/actions`, so
/// the two copies must stay identical and the source must exist.
#[test]
fn the_setup_action_is_owned_verbatim() {
    let source = read(".github-gen/sources/actions/setup-velnor-workflow/action.yml");
    let installed = read(".github/actions/setup-velnor-workflow/action.yml");
    assert_eq!(
        source, installed,
        "the setup action drifted from its source"
    );
    assert!(installed.contains("name: Set up Velnor workflow runtime"));
    assert_eq!(
        source
            .matches("--source-digest \"$manifest_revision\"")
            .count(),
        2,
        "manifest and asset attestations must bind the authenticated product revision"
    );
}

/// Activation is a protected-main operation. Its requested renderer and
/// published product must be in the dispatched main ancestry, the attestation
/// must name the exact product source digest, and a reused branch must be
/// current and contain only generated promotion output.
#[test]
fn activation_binds_provenance_and_rejects_stale_branch_content() {
    let source = read(".github-gen/sources/workflows/activate-renderer.yml");
    assert!(source.contains("ref: ${{ github.sha }}"), "{source}");
    assert!(
        source.contains("git merge-base --is-ancestor \"$REVISION\" \"$MAIN_SHA\""),
        "renderer dispatch must be bound to protected-main ancestry: {source}"
    );
    assert!(
        source.contains("git merge-base --is-ancestor \"$product_revision\" \"$MAIN_SHA\""),
        "published product provenance must be in protected-main ancestry: {source}"
    );
    assert_eq!(
        source
            .matches("--source-digest \"$product_revision\"")
            .count(),
        2,
        "the manifest and all supported assets must bind attestations to one exact source digest"
    );
    assert!(
        source.contains(
            r#"protected_tip="$(git ls-remote --refs origin "refs/heads/$DEFAULT_BRANCH""#
        ) && source.contains("protected $DEFAULT_BRANCH advanced"),
        "activation must reject a main branch that moved while publication was checked: {source}"
    );
    assert!(
        source.contains(r#"parent="$(git rev-parse "$branch_tip^")"#)
            && source.contains(
                "activation branch $branch is stale or contains more than one activation commit"
            ),
        "activation must reject stale or multiply-parented reuse branches: {source}"
    );
    assert!(
        source.contains(r#"git diff --name-only "$MAIN_SHA" HEAD"#)
            && source.contains(r#"grep -Fq "^$path	" "$state""#),
        "activation branch content must be limited to generated ownership output: {source}"
    );
}

/// The Rust unit workflow realizes exactly the backends its generated
/// project config declares: `github-hosted` renders the GitHub Mr. Boxington
/// backend, a local provider (`velnor`, `github-self-hosted`) renders the
/// local backend, and an undeclared backend must not appear.
#[test]
fn hosted_lane_uses_the_github_mb_boxington_backend() {
    let (_, workflow) = generated_files()
        .into_iter()
        .find(|(name, _)| name == "ci-unit-rust.yml")
        .expect("the rust kind reusable renders a workflow");
    let project = read(".github/ci/project.toml");
    let providers = project
        .lines()
        .find(|line| line.starts_with("providers = ["))
        .expect("project config declares its provider universe");
    let hosted = providers.contains("\"github-hosted\"");
    let local = providers.contains("\"velnor\"") || providers.contains("\"github-self-hosted\"");
    assert!(
        hosted || local,
        "project config declares no known provider: {providers}"
    );
    assert_eq!(
        workflow.contains("backend: github"),
        hosted,
        "hosted backend presence must match the declared provider universe: {providers}"
    );
    assert_eq!(
        workflow.contains("backend: local"),
        local,
        "local backend presence must match the declared provider universe: {providers}"
    );
}

/// The regeneration gate stays wired: the workflow crate's own unit watches
/// the runtime and the declared gate command checks the checked-out surface
/// with the same generator that produced it.
#[test]
fn the_regeneration_gate_is_declared() {
    let config = read(".github-gen/velnor-workflow.toml");
    assert!(config.contains("primitive = \"regen-gate\""));
    assert!(config.contains("--plain --check ../.."));
    let project = read(".github/ci/project.toml");
    let runtime_watched = project.lines().any(|line| {
        line.starts_with("watch = [") && line.contains("crates/velnor-workflow/src/runtime.rs")
    });
    assert!(
        runtime_watched,
        "the workflow crate unit must watch its runtime module"
    );
}
