//! The generated-surface contract of tailrocks/velnor.
//!
//! The generator is generic; this repository teaches it everything specific to
//! itself through `.github-gen/velnor-workflow.toml`. These tests hold the
//! lines that used to live inside the crate: the generator owns every
//! generated file under `.github`, the bootstrap action is owned verbatim,
//! and the self-hosted lane keeps its local Mr. Boxington backend.

use std::fs;
use std::path::{Path, PathBuf};

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .canonicalize()
        .expect("repository root resolves")
}

fn read(path: &str) -> String {
    fs::read_to_string(repository_root().join(path))
        .unwrap_or_else(|error| panic!("read {path}: {error}"))
}

fn generated_files() -> Vec<(String, String)> {
    let workflows = repository_root().join(".github/workflows");
    let mut files: Vec<(String, String)> = fs::read_dir(&workflows)
        .expect("read .github/workflows")
        .map(|entry| entry.expect("workflow entry").path())
        .filter(|path| path.extension().is_some_and(|extension| extension == "yml"))
        .map(|path| {
            let name = path.file_name().unwrap().to_str().unwrap().to_owned();
            let content = fs::read_to_string(&path).expect("read workflow");
            (name, content)
        })
        .collect();
    files.sort_by(|a, b| a.0.cmp(&b.0));
    files
}

/// The generated project config lists the workflow files it owns; every
/// checked-in workflow is one of them and carries the generator header, so a
/// hand-added workflow cannot hide beside the generated surface.
#[test]
fn the_generator_owns_every_current_workflow() {
    let project = read(".github/ci/project.toml");
    assert!(project.starts_with("# Generated by velnor-workflow."));
    let declared = project
        .lines()
        .find_map(|line| line.strip_prefix("files = ["))
        .map(|rest| rest.trim_end_matches(']').to_owned())
        .expect("project config declares its workflow files");

    let checked_in: Vec<String> = generated_files()
        .into_iter()
        .map(|(name, _)| name)
        .collect();
    for name in &checked_in {
        assert!(
            declared.contains(&format!("\"{name}\"")),
            "{name} exists under .github/workflows but the generated project config does not own it"
        );
    }
    for (name, content) in generated_files() {
        assert!(
            content.starts_with("# Generated by velnor-workflow."),
            "{name} is missing the generator header"
        );
    }
}

/// The bootstrap composite action is repository-owned bytes under
/// `.github-gen/sources`; the generator copies it into `.github/actions`, so
/// the two copies must stay identical and the source must exist.
#[test]
fn the_setup_action_is_owned_verbatim() {
    let source = read(".github-gen/sources/actions/setup-velnor-workflow/action.yml");
    let installed = read(".github/actions/setup-velnor-workflow/action.yml");
    assert_eq!(
        source, installed,
        "the setup action drifted from its source"
    );
    assert!(installed.contains("name: Set up Velnor workflow runtime"));
}

/// The self-hosted lane pins its Mr. Boxington backend to `local`, and the
/// hosted lane keeps `github`: backend selection is per lane, never global.
#[test]
fn velnor_lane_uses_the_local_mb_boxington_backend() {
    let (_, workflow) = generated_files()
        .into_iter()
        .find(|(name, _)| name == "ci-rust-velnor-workflow.yml")
        .expect("the workflow crate unit renders a workflow");
    assert!(
        workflow.contains("backend: local"),
        "velnor lane lost its local backend"
    );
    assert!(
        workflow.contains("backend: github"),
        "hosted lane lost the github backend"
    );
}

/// The regeneration gate stays wired: the workflow crate's own unit watches
/// the runtime and the declared gate command checks the checked-out surface
/// with the same generator that produced it.
#[test]
fn the_regeneration_gate_is_declared() {
    let config = read(".github-gen/velnor-workflow.toml");
    assert!(config.contains("primitive = \"regen-gate\""));
    assert!(config.contains("--plain --check ../.."));
    let project = read(".github/ci/project.toml");
    let runtime_watched = project.lines().any(|line| {
        line.starts_with("watch = [") && line.contains("crates/velnor-workflow/src/runtime.rs")
    });
    assert!(
        runtime_watched,
        "the workflow crate unit must watch its runtime module"
    );
}
