[nodes]
pegasus ansible_ssh_host=pegasus
delorean ansible_ssh_host=delorean
titan ansible_ssh_host=titan
sentry ansible_ssh_host=sentry
postgresql-nova ansible_ssh_host=postgresql-nova
clickhouse-selene ansible_ssh_host=clickhouse-selene

[nodes:vars]
ansible_ssh_user=root
ansible_ssh_common_args='-o IdentitiesOnly=no -o StrictHostKeyChecking=accept-new'
