- name: Upgrade Debian
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: auto_silent

  tasks:
    - name: Remove /etc/apt/sources.list if present
      file:
        path: /etc/apt/sources.list
        state: absent

    - name: Ensure required sources files are present
      copy:
        src: "debian/sources.list.d/{{ item }}"
        dest: "/etc/apt/sources.list.d/{{ item }}"
        mode: "0644"
      loop:
        - debian.sources
        - hetzner-mirror.sources
        - hetzner-security-mirror.sources

    - name: Check if docker.list exists on the server
      stat:
        path: /etc/apt/sources.list.d/docker.list
      register: docker_list

    - name: Replace docker.list with the repository version (only if it exists)
      copy:
        src: debian/sources.list.d/docker.list
        dest: /etc/apt/sources.list.d/docker.list
        mode: "0644"
        force: true
      when: docker_list.stat.exists
