# SPDX-FileCopyrightText: 2026 Alexey Zhokhov
# SPDX-License-Identifier: Apache-2.0

[package]
name = "jackin-tui"
version = "0.6.4"
edition.workspace = true
rust-version.workspace = true
publish = false

license.workspace = true
repository.workspace = true

[dependencies]
crossterm = { workspace = true }
jackin-brand = { workspace = true }
ratatui = { workspace = true }
termrock = { workspace = true }

[lints]
workspace = true
