HTTP/2.0 200 OK
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset, Warning
Cache-Control: private, max-age=60, s-maxage=60
Content-Security-Policy: default-src 'none'
Content-Type: application/json; charset=utf-8
Date: Sun, 20 Sep 2026 11:05:54 GMT
Etag: W/"5f09f3bbace0a4ffe2c12b623e6c26958a3c8f2843a987e6d55f24da3e9e1434"
Last-Modified: Sun, 20 Sep 2026 10:03:02 GMT
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Server: github.com
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
Vary: Accept, Authorization, Cookie, X-GitHub-OTP,Accept-Encoding, Accept, X-Requested-With
X-Accepted-Oauth-Scopes: repo
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Github-Api-Version-Selected: 2022-11-28
X-Github-Edge-Region: southeastasia
X-Github-Media-Type: github.v3; format=json
X-Github-Request-Id: 0518:A75D4:22AED4E:245E7CF:6AAFBE12
X-Oauth-Client-Id: 178c6fc778ccc68e1d6a
X-Oauth-Scopes: admin:org, delete_repo, gist, repo, workflow
X-Poll-Interval: 300
X-Ratelimit-Limit: 5000
X-Ratelimit-Remaining: 3902
X-Ratelimit-Reset: 1789902627
X-Ratelimit-Resource: core
X-Ratelimit-Used: 1098
X-Xss-Protection: 0

{"ref":"refs/heads/main","node_id":"MDM6UmVmMTkwNDE2NDYzOnJlZnMvaGVhZHMvbWFpbg==","url":"https://api.github.com/repos/actions/runner-images/git/refs/heads/main","object":{"sha":"9d7eec51794bb688d6c7ce00550cda5a134c88a3","type":"commit","url":"https://api.github.com/repos/actions/runner-images/git/commits/9d7eec51794bb688d6c7ce00550cda5a134c88a3"}}