[package]
name = "velnor-client"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Client-side transport contract for the Velnor control plane"

[dependencies]
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
velnor-model = { path = "../velnor-model", version = "0.1.0" }

[dev-dependencies]
[lints]
workspace = true
