[package]
name = "jackin-oppicker"
version = "0.6.4"
edition.workspace = true
rust-version.workspace = true
publish = false

license.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
crossterm = { workspace = true }
jackin-core = { workspace = true }
jackin-telemetry = { workspace = true }
termrock = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }

[lints]
workspace = true
